### ISSUE TITLE
TraitBank - Data download is not working (#1 post release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#102]

**Comment by KatjaSchulz** [comment]
Testing data downloads on beta.  Looks great, just one small thing.  Check out the Supplier column in this download file (type repository): http://services.eol.org/eol_php_code/applications/content_server/datasets/eol_download_1955.csv.zip

In addition to links to the MCZ site (which makes sense), there are many records which just list the number "33791."  I only see this in this particular download file.  Other downloads has sensible values in the Supplier column for all records.  

It looks like the Supplier column is populated from the http://purl.org/dc/terms/source field of the Darwin Core archive (why is it called Supplier then?).  When I look at some of the Supplier=33791 records on the beta website, it looks like they don't have a source value at all while others in the same data set do have the links to the MCZ site.  Compare for example, these two records:
With source link: http://beta.eol.org/pages/2937350/data#data_point_42379417
Without source link: http://beta.eol.org/pages/332440/data#data_point_42306876

Looking at this more closely, I note that all of the MCZ Entomology records I have looked at appear to have source links, while the MCZ Herpetology records don't.  So this may actually be a problem at the source.

The only problem on our end would then be that we are putting "33791" in the Supplier field when it should be empty.  And we are using the Supplier label for the Source field.  Maybe there's a good reason for that.

**Comment by JRice** [comment]
Okay, I think I'm done with this ticket. (KS and I talked about what she had in her comment; I think we're okay for now.)

I'm waiting for thumbs-up from SPG before releasing this. ...I'll leave it open in the spirit of its-open-until-its-live...

**Comment by jhammock** [comment]
Alas, our downloads in beta are not completing, at least, not yet. Some small, eg. my Bill Lengths request, 214 records, http://beta.eol.org/users/20470/data_downloads. Others longer, see http://beta.eol.org/users/35200/data_downloads

**Comment by jhammock** [comment]
My download reports completing at 9pm

**Comment by jhammock** [comment]
All the test downloads came in around 9pm except the largest, habitat (939064 results). It has been tagged with a "contact us" link, so I'm guessing it gave up. It was the first download in the bunch that was requested, so if they were processed in order, perhaps then all the others went through just fine? They look lovely, expected number of rows, all the expected metadata are present. If we just have a capacity limit, perhaps we put a warning and/or a block on requests for >X result downloads and work on lifting the limitation post release?

**Comment by JRice** [comment]
I doubt it's a capacity limit, but will have to check the logs. I _suspect_ it was improper behavior when trying to process something that had recently "been processed," but I'll have to check the code. :)  More later. ...Not working on this at the moment, stuck in adminland.

**Comment by JRice** [comment]
Okay, the code doesn't do anything if it's already been processed (which is a little sad; I wish it did, but I don't want to write it all right now).

I checked the logs and it looks like it was never picked up at all. ...which is ... odd. Could have been a glitch as I was restarting the worker or something. :S Best I can do is to run the job again (as my own user); it looks like it's it's running. I'll make sure it finishes with the expected number of rows (looks like a bit shy of a million).

**Comment by JRice** [comment]
Unfortunately, it looks like it is going to be a while processing this many rows. :(  Perhaps I SHOULD write some code to re-use existing files, if the search has already run. Let me see if that's hard...

**Comment by JRice** [comment]
Okay, I could only _partially_ implement that, because of the whole "we don't have a single shared drive" problem. ...On the positive side, we are presently only processing these from one server, so it should find previous runs more often than not.

So, good enough.

Also, FWIW, that million-row file is still processing, and is only about 5% done. :S So I guess this isn't super-fast.  :(  Sorry.  ...I suppose that's why it's in the background, eh?  :\

**Comment by jhammock** [comment]
No worries on the speed :) I wonder if these are processed single file? The timing of the last batch of completions suggests it. 

Oh- new batch of tests cancelled. More tomorrow.

**Comment by JRice** [comment]
Oh, sorry! I totally should have mentioned: yes, I ripped out the code that broke these up into separate files. A zipped million-line CSV file is still entirely servably-sized, so I figured that was safe, and we don't have the same limitations as we used to that forced us to break them up in days of yore.

I hope that was okay.

**Comment by JRice** [comment]
Well... it's still going. ...Juuuuust shy of half way done as of this writing, and still processing (I saw it go through a few queries just now).

**Comment by JRice** [comment]
Shoot, it crashed. But found a nice little rare bug.

```
** 03:27:29.384(8.82) TB.cache_query: trait_bank/search/http___rs_tdwg_org_dwc_terms_habitat/page/2439/per/200/desc (1600 results)
** 03:27:29.895(0.51) TB.cache_query: trait_bank/search/count/http___rs_tdwg_org_dwc_terms_habitat (939064)
.. 03:27:29.899 DSF: page 2439, count 487800, total 939064
!! 03:27:33.066(3.17) ERROR: undefined method `hidden?' for nil:NilClass
!! 03:27:33.066 /app/app/models/data_search_file.rb:85:in `block in get_data'
!! 03:27:33.066 /app/app/models/data_search_file.rb:84:in `each'
!! 03:27:33.066 /app/app/models/data_search_file.rb:84:in `get_data'
!! 03:27:33.066 /app/app/models/data_search_file.rb:107:in `write_file'
!! 03:27:33.066 /app/app/models/data_search_file.rb:19:in `build_file'
!! 03:27:33.066 /app/app/models/data_file_maker.rb:15:in `block in perform'
!! 03:27:33.066 /app/config/initializers/core_extensions_2.rb:424:in `block in with_master'
...
```

(Looks like a missing DataPointUri for a trait.)

Will fix later.  I hate to re-run this, but... :\

**Comment by JRice** [comment]
Started it again just now (busy day with interrupts).

**Comment by JRice** [comment]
Yup, works now. I'm calling this "ready" ...but not closing it until it's deployed. (?)

**Comment by jhammock** [comment]
Hmm... I just tried a couple of test downloads and the first one came back empty. http://beta.eol.org/users/20470/data_downloads  Is this not hooked back up in beta yet?

**Comment by JRice** [comment]
Nono, it is. That's a bug (re-running a search that it's already done). Thanks, I'll look into later.

**Comment by JRice** [comment]
Aaaaacutally, it looks like it *does* work and the site's "auto-redirection" is not working. Blast! ...But probably a separate ticket, sadly...

**Comment by JRice** [comment]
Okay, now we have two (new) problems.

1. The merges to 0 were, in fact, bad. :S Need to fix those... and that may not be super simple. Sigh. (FWIW: I added a bunch of code to ensure it wouldn't happen again, buuuuuuuut....)
2. The code doesn't move traits over, and it needs to. I'll have to write that code (from scratch). Eeep.

**Comment by jhammock** [comment]
Just tried a new (not previously searched) [search](http://beta.eol.org/data_search?utf8=%E2%9C%93&taxon_concept_id=&attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FOBA_1000133&taxon_name=&commit=Search) in beta

Not seeing it in my [profile](http://beta.eol.org/users/20470/data_downloads)

**Comment by jhammock** [comment]
Ah- the new search did not appear in the queue immediately, but it completed and appeared a few hours later. The "re-running a search that it's already done" bug is still present.

**Comment by jhammock** [comment]
And now I'm afraid the Download button is missing

**Comment by JRice** [comment]
I think this is resolved; I think this is ready to be deployed. ...But I shall await your confirmation.

**Comment by jhammock** [comment]
Alas, this may only have worked for a week. Sorry, testing was intermittent, but fails started around March 28. See top two downloads at http://eol.org/users/20470/data_downloads

**Comment by JRice** [comment]
If you see jobs in the "data" queue at http://eol.org/admin then there is still hope; it just means the worker is offline.

I've had it offline as I work on TB stuff. ...I should put it back, though... will do later today.

**Comment by jhammock** [comment]
Cool :)   Yeah, 11 jobs. This is not (yet!) a heavily subscribed feature
