### ISSUE TITLE
[2] TraitBank - units are not displayed (needed for release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#103]
Units do not show in either the data row or the expanded record. All other metadata appear to be present in their appropriate places.

**Comment by JRice** [comment]
Shoot! I'd forgotten to write the methods to render them.

Relatively easy, though, thanks to the simplicity of the new system. ;)  Done.  I might be missing some features from the old code, but I was sure to convert things after "^"s to superscripts.
