### ISSUE TITLE
[8] TraitBank - restore harvesting version (by YA) of normalizing units during harvests and test it at scale

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#106]

**Comment by jhammock** [comment]
see: https://github.com/EOL/tramea/issues/135
This may mean normalized numerical values will not completely solve the sorting problem.

**Comment by JRice** [comment]
FWIW, what I expect this script to do is to look for all triples containing units that are NOT in our preferred normalized forms, convert them to said preferred units, and add those as new triples.

Ideally, this should be able to run on a single resource at a time, and it should only run on batches of triples (how large depends on performance and the limits of Virtuoso (which can only work on 10,000 triples at a time, if I understand correctly)... my _guess_ would be about 1000 at a time).

**Comment by YoustinaAtef** [comment]
https://github.com/EOL/eol_php_code/compare/normalized_data
