### ISSUE TITLE
[1] Web interface access for BibAlex team to App A

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#111]

**Comment by JRice** [comment]
[beta.eol.org](http://beta.eol.org)

It's open access, which is fine, though we shouldn't "advertise" it much. ...It's production data, which is fine (nothing you can do here that you can't in the real world). It's a beta site, so it's likely to be up and down as developers tweak the server itself.

To the developers: you can push your code to the "docker" branch of eol, then log into the app1 host, then to the "appa" container. From there, you can `git pull` to get the latest code, and restart the workers with the following:

```
for id in `ps -ef | grep "unicorn worker" | grep -v "color" | awk '{print $2;}'`; do echo $id; kill $id; sleep 10;
done
```

**Comment by JRice** [comment]
One thing to note: assets are "shared" on this server with the rest of production, so changes to JS or CSS will NOT (!) show up here until they show up everywhere.

Deal with that.  Sorry!
