### ISSUE TITLE
Slow User Pages

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#12]
It turns out there are some _seriously_ slow pages that are bogging down the site. ...Yes, yes, we all know about the data tab, and we're all working to fix those. However, one of those pages is user pages.

Yes, user pages.

Only for really active Users, though!  For example:

![screen shot 2015-09-25 at 9 04 53 am](https://cloud.githubusercontent.com/assets/24174/10101253/9d2466d2-6365-11e5-8318-ae1e6bfb5193.png)

...As you can see, Dr. Hogan has thousands of curations and the like.

This is easily fixed, so I'll make this a task: add counter_culture where appropriate. We're using it in only a couple of places now (collection items comes to mind), and here's a great place to use it again.

It won't work on comments (because they are polymorphic) and it might not work on the breakdowns of curation types (not sure, but a clever use of scope might be enough). ...For those cases, we'll have to write some custom code to do the counting, just be sure:

a) that the count is incremented when a new action is taken, and
b) there is a method to "reindex" (re-count) all of these user counts.

...Speaking of (b), we should add a "reindex" button to the top of the user page (for admins) to call this method. ...There are plenty of examples of this in the code... look at a data_object, for one. In involves a new controller action and a new route, and of course adding the button to the view and the method to the model. ...But that's it.

**Comment by JRice** [comment]
Add a paragraph under "Activity" that says "Counts are refreshed daily."

**Comment by AmrMMorad** [comment]
Kindly find a solution for this using caches and counter culture. Also reindex button is added to the users page for admins in order to refresh these counts:
https://github.com/EOL/eol/compare/git-12
Also kindly find a sample run for users page (note admin user was signed in).
![user_counts](https://cloud.githubusercontent.com/assets/9263535/10753424/8ff0790e-7c99-11e5-8bf7-c2ee1a625cba.png)

**Comment by JRice** [comment]
FWIW: it still took a long time to load this page, on the first load. It was quite fast on the second load, though.

Perhaps we should have a conversation with SPG about these stats, and see if we can reduce the number of complex stats that we're calculating.

**Comment by AmrMMorad** [comment]
I think this was somehow expected as it uses cache mainly so it will take long time on first load. I think we can show 4 or 5 counters in user profile page and add "show more" link where the user can view all the statistics count. By this way, user can revoke a permission or view other tabs without having to wait this time.. What do you think?
