### ISSUE TITLE
[3] Collection Dialogue Box Order

### ISSUE THREAD

**Issue by mariestuder** [EOL/tramea#123]
When adding a page, image, etc. to a Collection the most recently updated Collection should appear first in the list in the dialogue box.

**Comment by HudaSoliman** [comment]
Hi Marie, 
I'll keep the watch collection listed first then the rest of the collections will be listed according to the most recent updated time. Is that okay?

**Comment by mariestuder** [comment]
Hi Huda!

Thanks very much for your question.  I've just asked the L+E group (Jeff, Tracy and Amy) to give their input on this and here is our collective preference:
1.  Do as you suggest (Keep the Watch List Collection first and then have the rest of the collections listed according the most recent updated time).  But, this should only happen if a user can quickly sort the collections alphabetically, in case they need to find a different Collection to work on.  Otherwise it will be too hard to find the Collections.
2.  If is isn't possible to quickly sort the Collections alphabetically, then we would prefer that the Watch List is first, then the most recently used Collection and the rest should be in alphabetical order. 

By the way, none of us use our Watch Lists. We might want to figure out what they are really meant to do and if anyone uses them.  It's OK to keep the Watch List first for this version, but we may want to rethink them.

Thank you very much!  This is a feature we've been dreaming about for several years and it will be amazing if you can help us to get it done!

Please ask if you have questions.

Best,
Marie

**Comment by HudaSoliman** [comment]
I made it as in the 1st suggestion: Keeping the Watch List Collection first and then have the rest of the collections listed according the most recent updated time with the possibility of sorting the collections alphabetically, as in the photos:  
![collections 1](https://cloud.githubusercontent.com/assets/10114312/13251820/15fa6146-da3b-11e5-9740-87307beaa82d.png)
![collections 2](https://cloud.githubusercontent.com/assets/10114312/13251821/15feec02-da3b-11e5-8745-036ef37bfefd.png)

the code for this task is on this branch : https://github.com/EOL/eol/tree/git-123_collection-order-in-dialogue

**Comment by mariestuder** [comment]
This looks absolutely perfect!  Thank you.  This is complete.
