### ISSUE TITLE
Test the load of batch API use and restrict sizes if needed

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#126]
Of concern for https://github.com/EOL/tramea/issues/40, which is now available

**Comment by hyanwong** [comment]
I'm about to code up a site that asks for info on batches of (maximum) 50 pages, just to get the common name and best pd|cc-by|cc-by-sa image available. E.g. 

http://eol.org/api/pages/1.0.json?batch=true&id=1178406%2C1178405%2C1178408%2C1178407%2C1178399%2C1178400%2C1178403%2C1178402%2C1178401%2C663227%2C1178398%2C1178416%2C1178414%2C1178418%2C1178415%2C1178412%2C1178417%2C1178378%2C1178386%2C1178384%2C1178383%2C1178377%2C1178385%2C1178379%2C1178388%2C1178397%2C1178381%2C1178387%2C1178396%2C1178392%2C1178395%2C1178380%2C1178389%2C1178390%2C1178393%2C1178382%2C1178394%2C1178391%2C1178409%2C1178411%2C1178410%2C1178372%2C1178376%2C1178373%2C1178374%2C1178375%2C1178371%2C1178370%2C130164%2C&images=1&videos=0&sounds=0&maps=0&text=0&iucn=false&subjects=overview&licenses=pd%7Ccc-by%7Ccc-by-sa&details=true&common_names=true&synonyms=false&references=false&taxonomy=false&vetted=1&cache_ttl=10000

Is this too much for the API? I'm guessing not, but will rein in the numbers if it's a problem. Note that this batch request isn't called repeatedly in a loop, only a single time when someone visits a particular page (although there are lots of potential pages to visit).

**Comment by jhammock** [comment]
If nobody pipes up with a more alarmist view, (cough @jrice cough) this sounds like a great test to me...

**Comment by JRice** [comment]
I say Go For It™. We'll notice pretty quickly if you've ruined our lives.

Sorry for the cop-out answer; limited time to run my own tests. :S

**Comment by hyanwong** [comment]
Not a cop out at all. Perfectly reasonable. I'll let you know on this issue when I start testing it seriously.

**Comment by jhammock** [comment]
@hyanwong just checking- if you've tried this yet, how is it behaving for you? Thanks!
