### ISSUE TITLE
TB search results- selecting any page of results shows page 1 results (needed for release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#127]
eg: http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256&commit=Search&page=2&sort=desc&taxon_concept_id=&taxon_name=&utf8=%E2%9C%93

**Comment by JRice** [comment]
Ooops, I broke that when merging code, and then was cleaning up the controller for some other stuff, and it ended up out of sync with the search class. My mistake. Fixed now.
