### ISSUE TITLE
Unitless body length Pantheria records- find units or hide records (needed for release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#128]
In this resource, http://beta.eol.org/content_partners/652/resources/704

Just one measurementType seems to be missing its units: body length (http://purl.obolibrary.org/obo/VT_0001256)

Not all body length records are unitless; it might just be adult records, based on a small sample. http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256

This ticket may be blocked by https://github.com/EOL/tramea/issues/127  Further diagnosis would be easier if we could look at more of this dataset.

**Comment by JRice** [comment]
#127 is fixed, if that helps.

I'll have to work on this later; gotta close up shop for tonight. But the beta site is back up, at least.

**Comment by jhammock** [comment]
It's only the adult records. If LifeStage= any other value or is not specified, the units appear.

**Comment by JRice** [comment]
Something stinks about these data. Weirdly, when I look at the file, I see the measurements, but the predicate is different—it's http://purl.obolibrary.org/obo/VT_0001259 not http://purl.obolibrary.org/obo/VT_0001256. ...I don't know the difference off-hand, but that's a surprise. The units are there in the file (full checkL: they are _all_ http://purl.obolibrary.org/obo/UO_0000021 ), but the difference in predicate bothers me... I'm tempted to look into the "old data" version to see what was up with it... but I suppose I can just insert these units for now as a patch...

**Comment by JRice** [comment]
Well that was a failure. :(  I added the units ... where were GRAMS.

...Which is a little awkward for measuring Body Length. 

I've deleted all those triples I inserted. [sigh] I'll have to come at this again tomorrow, sorry!

**Comment by JRice** [comment]
My mistake. :( Should have been (and they all are) http://purl.obolibrary.org/obo/UO_0000016

**Comment by JRice** [comment]
Okay, appears to be fixed.
