### ISSUE TITLE
[0.5d] Data Downloads—Contact Us Link if Older than 4 Hours

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#13]
Let's stop having people email us angrily when DataSearchFile processing fails. If a file is not completed and it was started > 4 hours ago, add a link (where the "download" link would be) saying "This file has not processed yet, please contact us for assistance." ...And the link should, of course, go to the usual contact us jobby.

**Comment by AmrMMorad** [comment]
The changes is committed under:
https://github.com/EOL/eol/compare/git-13
Also kindly find the following screenshot for the user downloads:

![git-13](https://cloud.githubusercontent.com/assets/9263535/10867536/c545e934-806f-11e5-8d72-58a46aaa7910.png)

but I see that this statement may be long to be a link, I see it somehow weird.. what do you think?

**Comment by AmrMMorad** [comment]
Well there are some other suggestions for the view as follows:
Suggestion # 1:
![suggestion1](https://cloud.githubusercontent.com/assets/9263535/10903626/69973a10-8214-11e5-954d-de0a674cdc11.png)
Suggestion # 2:
![suggestion 2](https://cloud.githubusercontent.com/assets/9263535/10903633/76f9761e-8214-11e5-84aa-34849a1d2855.png)
Suggestion # 3:
![suggestion3](https://cloud.githubusercontent.com/assets/9263535/10903638/7d9aae20-8214-11e5-90b1-89bad6cc223c.png)
For me I like suggestion # 2 more but this can be changed easily, What do you prefer?

**Comment by JRice** [comment]
I see. Actually, I think #2 is a little bit confusing—it's not immediately
obvious that, because the file has not processed, you should contact us.
That's clearer in the third option, which I like. The link there is
(perhaps unintentionally) upcased too, which I think adds to the importance
of it.

Could you use that one?

Thanks.

**Comment by AmrMMorad** [comment]
Yes sure. I committed the latest changes on the branch:
https://github.com/EOL/eol/compare/git-13

Thanks

**Comment by JRice** [comment]
Looks good. Could you merge to master?

**Comment by AmrMMorad** [comment]
Sure. I did now..
Thanks
