### ISSUE TITLE
[1] TraitBank - Search "Equivalent values" doesn't actually work (post release)

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#131]
...Should be (really) easy to add this, but we also have the option of hiding it, if we want to release more quickly.

**Comment by JRice** [comment]
e.g. [This search](http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256&sort=desc)

**Comment by jhammock** [comment]
I could wait til post release for this. @KatjaSchulz?

**Comment by KatjaSchulz** [comment]
I agree, this can wait.

**Comment by KatjaSchulz** [comment]
Currently, the data search page still pretends that it can do equivalent value searches.  It says:
 "Equivalent values: (search again to include selected attributes)"
and lets you check boxes of terms to search.
But then when you do the search, it doesn't work, of course.  You get the same records as before.

We may want to consider taking out anything referring to the equivalent search until it has been reinstated.

**Comment by AmrMMorad** [comment]
Do we really need to remove the equivalent search? or check why this feature isn't working?

**Comment by jhammock** [comment]
Sorry, the above chatter is unclear. It is worth trying to get this feature working. If it looks like more than a one unit task, though, hiding the feature will do.

**Comment by menna-hedaia** [comment]
The search now returns the results of the attribute and its equivalent. Here are screen shots for search using a single attribute and another with its equivalent.
![1_att](https://cloud.githubusercontent.com/assets/15714220/13279101/d7b6dde4-dadd-11e5-880f-3e4243c3bcc6.png)
![2_att](https://cloud.githubusercontent.com/assets/15714220/13279107/de63a456-dadd-11e5-8a67-2e12d04632ee.png)
The code is in the following branch 
https://github.com/EOL/eol/commit/26afed2373672a0ba69fba03e5787f7ec4357cc2

**Comment by jhammock** [comment]
How satisfying :) I should go into the terms interface and see if we need any new equivalence relationships.
