### ISSUE TITLE
[3] Make login?return_to= links work even if user is logged in

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#132]
At the moment, something like

http://eol.org/login?return_to=http%3A%2F%2Feol.org%2Fdata_objects%2F12506400

takes you to the login page, then to http://eol.org/data_objects/12506400 . But if you are already logged in, it takes you to your user page, regardless of the return_to value. I suggest it should simply redirect you straight to the return_to page if you are already logged in.

**Comment by JRice** [comment]
Put another way: for the login controller action, if the user is already logged in and there is a "redirect to" in the parameters, simply redirect the user to that page.

**Comment by hyanwong** [comment]
Yes, perfect. Would love this to be implemented soon

**Comment by menna-hedaia** [comment]
Done. You can find the solution on this branch
https://github.com/EOL/eol/commit/dcb5af28ca7bbac673799bf12d73e24552ad697c

**Comment by JRice** [comment]
That looks fine. Could you merge to master, please?

**Comment by menna-hedaia** [comment]
Done

**Comment by jhammock** [comment]
Have I applied that pretty new label appropriately?

**Comment by hyanwong** [comment]
It works. Lovely. Thanks.
