### ISSUE TITLE
Metadata impacts within-page sort of TB search results (post release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#135]
The current sort of numerical values, not between search result pages, only locally within a page, is affected by metadata, eg: lifestage records are sorted alphabetically, (blank lifestage at the end) before values are sorted within a lifestage category: http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256&page=11

Other effects are less clear to me but may still involve metadata, including statisticalMethod: http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256&page=30

**Comment by jhammock** [comment]
Supplier name may be sorted before anything else, again, only within one page of results:

http://beta.eol.org/data_search?attribute=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FVT_0001256&page=29

Within the records with supplier=Birds Animal Diversity Web, I can't find any pattern they could be sorted on, in any page of results. Between pages of search results, though, these records are also neatly descending by body length value, as expected

**Comment by YoustinaAtef** [comment]
So, what you want is to sort globally by value and to sort within the page by (life stage, sex and statistical method), the result then will be
- all values in first page are greater than any other page.
- within the same page traits are sorted according to (life stage, sex and statistical method).
  is that right?

**Comment by JRice** [comment]
Bah! My fault... I didn't do a proper job of sorting here. :S  Sorry!

**Comment by jhammock** [comment]
Oops, that was unclear of me. The description at the top is the behavior _I see currently_. The desired behavior is for records to sort by value, and ignore metadata, both within and between pages.

**Comment by YoustinaAtef** [comment]
done and pushed to master
