### ISSUE TITLE
Link objects created manually do not show in taxon pages

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#136]
For instance: http://eol.org/data_objects/33093535 does not appear in http://eol.org/pages/1016697/resources

Some previously manually added links are displaying just fine, eg: http://eol.org/pages/1553/resources/citizen_science

A user is trying to add link objects and has noticed this problem; otherwise it might have waited indefinitely.

**Comment by jhammock** [comment]
Jen should inform Nick when this is fixed http://eol.org/users/20470/newsfeed

**Comment by HudaSoliman** [comment]
I checked the link and found its languange is Deutsch, the page only shows the links with the current displaying language.
So, you can see it when you change the language of the site to Deutsch.

**Comment by jhammock** [comment]
Of course! Thank you, Huda. I will explain to the user
