### ISSUE TITLE
apple-touch-icon.png

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#139]
Two of the most frequent errors we see in the production log (by FAR) are:

```
ActionController::RoutingError (No route matches [GET] "/apple-touch-icon.png"):
ActionController::RoutingError (No route matches [GET] "/apple-touch-icon-precomposed.png"):
```

...This is low-hanging fruit to fix (add routes to a suitable image), and might make 0.0001% of our users' experiences slightly better (it will allow them to save EOL links to their "home screen" on iOS... yaaaay).  :-|

You can read about such things [on the web](https://developer.apple.com/library/ios/documentation/AppleApplications/Reference/SafariWebContent/ConfiguringWebApplications/ConfiguringWebApplications.html) in [various](http://stackoverflow.com/questions/14986650/keep-getting-404s-for-apple-touch-icon-png) [places](https://realfavicongenerator.net/blog/apple-touch-icon-the-good-the-bad-the-ugly/)... It would behoove us to stop getting these errors (they really clutter the log and presumedly slow down users' experiences slightly).

**Comment by YoustinaAtef** [comment]
I added them to the routes file but I can't test this locally
https://github.com/EOL/eol/tree/apple_touch_icon

**Comment by JRice** [comment]
Can we merge this to master, to see if it works with the next deploy?

**Comment by YoustinaAtef** [comment]
Done

**Comment by jhammock** [comment]
oh, this is probably deployed now. Does it work?

**Comment by jhammock** [comment]
@jhammock will open a ticket for the new errors:

apple-touch-icon-120x120.png
/apple-touch-icon-120x120-precomposed.png
/apple-touch-icon-152x152-precomposed.png
/apple-touch-icon-152x152.png
