### ISSUE TITLE
[1] TraitBank - API

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#140]
e.g. http://eol.org/api/traits.json?id=328674 ...should return pretty much what one gets via the ld+json.

...We ONLY need to implement the json for this API, it's not an "open" API at this point.

**Comment by jhammock** [comment]
Uh oh... The content of the service is incomplete (MeasurementType is missing) and has some spurious things in it (username and password, both null). eg: http://eol.org/api/traits/1264966

It's also shaky at the moment- perhaps affected by the same conditions as the other apis? But I will generally get a response after a few tries.

**Comment by JRice** [comment]
Whoa, yeah, the @id is completely wrong. Weird.

Not sure about measurementType missing... (I see it as @type, which is how we used to store it, so I copied that) could you give an example?

**Comment by JRice** [comment]
Okay, fixed the ID.

Note to self: the "measurementType" is the **predicate**! ...Which is totally missing. Weird!

I'll assume we want both the URI and the name in there, somehow... though I'm not entirely sure where to put that. Hmmmn.

**Comment by JRice** [comment]
Found and fixed the problem. I've added the dwc:measurementType key for the URI version of the predicate, and also a predicate to store the human-readable (English) name for it.

While there, I also added units for the readable version of the units, when available/salient, and value for the value (which is sometimes purely a URI).
