### ISSUE TITLE
Data Downloads "cancel" button doesn't work

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#142]
Results in a 404 "Not Found" error. The URL doesn't even look right, something like `http://eol.org/users/1/data_downloads/1945?type=0` ...I would expect something like `http://eol.org/users/1/data_downloads/delete?id=1945` (or something like that... technically it should be a POST, but I don't care enough to force us to do that, cause it's a bit of a PITA).

**Comment by HudaSoliman** [comment]
Fixed it on this branch https://github.com/EOL/eol/commit/1bc1344fb56003a76712323620023e844191555a

**Comment by JRice** [comment]
Merged to docker branch (where I'm testing new features)... will be on
master later today.
