### ISSUE TITLE
homepage activity feed is not refreshing

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#146]
This list of actions has been up for at least a few days

Tatiana Remizova commented on "Bathyraja spinicauda (Jensen, 1914)":
Шипохвостый скат
ABOUT 3 HOURS AGO

C. Michael Hogan marked the classification from "Species 2000 & ITIS Catalogue of Life: April 2013" as preferred for "Civettictis civetta (Schreber, 1776)".
ABOUT 6 HOURS AGO

Dana Campbell set "Image of Cribrarula cumingii" as an exemplar on "Cribrarula cumingii (G.B. Sowerby I, 1832)".
ABOUT 9 HOURS AGO

Peter Halasz commented on "Pteronotus paraguanensis":
Pteronotus parnellii paraguanensis. should be listed as a synonym. e.g. "Pte... more
ABOUT 10 HOURS AGO

Jennifer Hammock commented on "File:Oreaster nodosus - Osaka Museum of Natural History - DSC07831.JPG":
ID courtesy Frédéric Ducarme and Chris Mah
ABOUT 14 HOURS AGO

Nick Durmuller added the French common name "Lactaire humide" to "Lactarius uvidus (Fr.) Fr. 1838".
ABOUT 20 HOURS AGO

**Comment by JRice** [comment]
FWIW, I _just_ cleared the cache (accidentally) which would fix this problem... temporarily. Please do keep an eye on it—I suspect the recent work on clearing the cache when a user is deleted may have altered the expiration time on that.  ...And/or we could modify the activity logger such that when something SHOULD go on the homepage, it clears that cache. ...Whatever works.

**Comment by jhammock** [comment]
New list:

Amy Lorenz added "Hyla cinerea (Schneider, 1799)" to the collection "Common Amphibians of Okaloosa County".
1 MINUTE AGO

Jennifer Hammock changed the thumbnail image of "Lateral view".
1 MINUTE AGO

Jeff Holmes changed the thumbnail image of "Aspidoscelis_costata".
16 MINUTES AGO

Jeremy Rice changed the thumbnail image of "Spined Assassin Bug - Sinea diadema".
22 MINUTES AGO

Megan Wannarka added "Lavandula latifolia Medik." to the collection "Apis mellifera pollinator for plant".
34 MINUTES AGO

Nick Durmuller added a link to "Characteristic features of hygrophorus purpurascens (pictures and text)" on "Hygrophorus purpurascens (Alb. & Schwein.) Fr. 1838".
Guidance for identification (German text)
38 MINUTES AGO

**Comment by jhammock** [comment]
(That activity list is unchanged the following day)

**Comment by YoustinaAtef** [comment]
You can find the solution for  this bug on this branch
https://github.com/EOL/eol/compare/refresh_activity_logs_in_homepage

**Comment by JRice** [comment]
That will work, but it points out we have some really tight coupling between this view, `ApplicationController#clear_cached_homepage_activity_logs` and `ContentController#periodically_recalculate_homepage_parts` ...at the very least; there could be other places. Sloppy code. :(

When we're working on Tramea, let us remember that any time we set a cache, we need a _centralized_ way to save the name (and or save/clear it), so we can clear it safely from multiple places if necessary. :\

**Comment by jhammock** [comment]
This feed is frozen again. I'd hate for someone to really sweat over this. Anything easy we can do to "sort of" fix it, until Tramea?

**Comment by JRice** [comment]
I'm taking this one over!

**Comment by JRice** [comment]
This appears to be working, actually. I'm closing it.

**Comment by jhammock** [comment]
hmm... I think we're stuck again...

**Comment by JRice** [comment]
Oooooh. Yeah, sorry. My mistake.

**Comment by JRice** [comment]
Found the problem... this should have been around for years, but was "worked around" by some REALLY TABLE-FLIPPINGLY STUPID CODE (which used Rails.cache in layers) which I recently removed.

Anyway, should really be fixed. I pushed this ONE change to production already.
