### ISSUE TITLE
CORS has stopped working for API

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#147]
Issue https://github.com/EOL/tramea/issues/41 seems not to have been resolved (or has come back), so it is no longer possible to make API requests from a separate web page. To test, you can use http://client.cors-api.appspot.com/client e.g. [For the example on the search_by_provider API](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Feol.org%2Fapi%2Fsearch_by_provider%2F1.0%2F180542.json%3Fhierarchy_id%3D903&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote) or the [pages API](http://client.cors-api.appspot.com/client#?client_method=GET&client_credentials=false&server_url=http%3A%2F%2Feol.org%2Fapi%2Fpages%2F1.0.json%3Fbatch%3Dfalse%26id%3D1045608%26images%3D2%26videos%3D0%26sounds%3D0%26maps%3D0%26text%3D2%26iucn%3Dfalse%26subjects%3Doverview%26licenses%3Dall%26de&server_enable=true&server_status=200&server_credentials=false&server_tabs=remote)

**Comment by hyanwong** [comment]
So has this been solved now. What was the problem? And when is the solution going live?

**Comment by jhammock** [comment]
Ah, sorry, @hyanwong. Implementing new ticket protocol...

**Comment by hyanwong** [comment]
Ah - like the new protocol w/ milestone. Thanks. Is it worth implementing a unit test in case it happens again @AmrMMorad ?

**Comment by AmrMMorad** [comment]
@hyanwong I think we may not need this for now as it was initially implemented to work on WAPI only. I guess this was the main problem. I did generalize it to work on normal API. I intended to test it using the tool that you kindly provide. If we face another problem, we can implement unit test for it. Thanks.

**Comment by hyanwong** [comment]
@AmrMMorad thanks. I see it is still not working on the live site, though. Presumably just waiting for deploy.

**Comment by AmrMMorad** [comment]
@hyanwong yes it is waiting for the next deploy. Thanks a lot

**Comment by rjsteen** [comment]
When will the next deploy be?

**Comment by rjsteen** [comment]
@AmrMMorad : when will the next deploy be?

**Comment by JRice** [comment]
Ooof. I'm super-busy, so ... tomorrow at the earliest. Maybe early next week, depending on priorities. I will let you know.  :)

**Comment by JRice** [comment]
Indeed, it looks as if this is an insidious bug in the harvesting code. Any taxa that are "touched" by a harvest right now and have TOC items that are there WITHOUT "info items" (long story, if you don't know, but basically anything added by a user counts) will lose their TOC items. Entirely. Gonzo.

This isn't a trivial fix, I'll need to really think about this, but A) I won't harvest anymore until it's fixed, B) I will kill the running harvest, and C) I will fix the bug tomorrow.

...That is still going to leave a TON of data objects "floating" out there with no TOC items. ...which we should talk about how to deal with.  :(  Sorry!

**Comment by JRice** [comment]
I think I've fixed the bug, will test it out tomorrow.

**Comment by JRice** [comment]
...Waiting to test until I can be positive I've backed up the information we have. :(

**Comment by rjsteen** [comment]
Thanks for the help @JRice !

**Comment by JRice** [comment]
FWIW, I still have not had a chance to deploy yet. I will struggle to get it in this week, though. :(

**Comment by JRice** [comment]
I've deployed. I'm not sure what to look for, could someone else check this?

**Comment by iimog** [comment]
It works. Thank you!

**Comment by rjsteen** [comment]
Thanks!
