### ISSUE TITLE
[4d] Taxon OpenData

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#15]
we need an OpenData dump of taxonomic information. We have a rake task for this, but it takes too long to run. Review and improve efficiency.

(If this BASIC INFORMATION cannot run quickly, then we have an underlying structural problem and need to address it.)

**Comment by YoustinaAtef** [comment]
The performance is improved by 30%, I can't find any other enhancment. what else should be done in this task?
you can find it at https://github.com/EOL/eol/tree/opendata%2315
