### ISSUE TITLE
[SI] Evaluate performance of slave1 vs slave2 and slave3 (HEAT ticket 01081788)

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#150]
Basic tasks (unzipping, scp'ing) seem to be running _very_ slowly (to me) on slave1. I'd like to know why.

Suggest we install and run sysbench to see if there's a real difference, then investigate, if there is.

**Comment by JRice** [comment]
I actually started this by testing cpu on on slave1:

```
[jrice@eol-db-slave1 ~]$ sysbench --test=cpu --cpu-max-prime=20000 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1

Doing CPU performance benchmark

Threads started!
Done.

Maximum prime number checked in CPU test: 20000


Test execution summary:
    total time:                          23.4296s
    total number of events:              10000
    total time taken by event execution: 23.4289
    per-request statistics:
         min:                                  2.34ms
         avg:                                  2.34ms
         max:                                  2.71ms
         approx.  95 percentile:               2.34ms

Threads fairness:
    events (avg/stddev):           10000.0000/0.00
    execution time (avg/stddev):   23.4289/0.00
```

**Comment by JRice** [comment]
Errr... I should mention, I'm mostly following [this tutorial](https://www.howtoforge.com/how-to-benchmark-your-system-cpu-file-io-mysql-with-sysbench) (using yum instead of apt-get, of course).

**Comment by JRice** [comment]
CPU on slave2 (not actually a tad slower, but barely):

```
[jrice@eol-db-slave2 ~]$ sysbench --test=cpu --cpu-max-prime=20000 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1

Doing CPU performance benchmark

Threads started!
Done.

Maximum prime number checked in CPU test: 20000


Test execution summary:
    total time:                          24.6673s
    total number of events:              10000
    total time taken by event execution: 24.6665
    per-request statistics:
         min:                                  2.34ms
         avg:                                  2.47ms
         max:                                  7.01ms
         approx.  95 percentile:               3.06ms

Threads fairness:
    events (avg/stddev):           10000.0000/0.00
    execution time (avg/stddev):   24.6665/0.00
```

**Comment by JRice** [comment]
slave2 disk test finished first even though it was started much later:

```
[jrice@eol-db-slave2 ~]$ sysbench --test=fileio --file-total-size=150G --file-test-mode=rndrw --init-rng=on --max-time=300 --max-requests=0 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Initializing random number generator from timer.


Extra file open flags: 0
128 files, 1.1719Gb each
150Gb total file size
Block size 16Kb
Number of random requests for random IO: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random r/w test
Threads started!
Time limit exceeded, exiting...
Done.

Operations performed:  51663 Read, 34442 Write, 110208 Other = 196313 Total
Read 807.23Mb  Written 538.16Mb  Total transferred 1.3139Gb  (4.4845Mb/sec)
  287.01 Requests/sec executed

Test execution summary:
    total time:                          300.0088s
    total number of events:              86105
    total time taken by event execution: 297.5101
    per-request statistics:
         min:                                  0.01ms
         avg:                                  3.46ms
         max:                                702.78ms
         approx.  95 percentile:              17.43ms

Threads fairness:
    events (avg/stddev):           86105.0000/0.00
    execution time (avg/stddev):   297.5101/0.00
```

As I understand it, the important piece of information here is the **4.4845Mb/sec**.

**Comment by JRice** [comment]
I'm not going to run the suggested mysql test right now... the problem seems pretty clearly to be I/O, so I'll wait until that's resolved...

**Comment by JRice** [comment]
Bah, now things are _truly_ screwed up.

I got this:

```
[jrice@eol-db-slave1 ~]$ sysbench --test=fileio --file-total-size=150G prepare
sysbench 0.4.12:  multi-threaded system evaluation benchmark

128 files, 1228800Kb each, 153600Mb total
Creating files for the test...
FATAL: Failed to write file! errno = 5 ()
[jrice@eol-db-slave1 ~]$ df -h .
Filesystem            Size  Used Avail Use% Mounted on
/dev/mapper/rvol_vg-rvol00
                      1.1T  758G  271G  74% /
```

...I then tried to remove a (very) large file in my homedir to open up more space, to see if that would help, and got this:

```
[jrice@eol-db-slave1 ~]$ rm eol-all-sql-2016-02-04
-bash: /bin/rm: Input/output error
```

Eeep. I'm leaving it alone, now. Seems the disk has failed.

**Comment by JRice** [comment]
Mary says: "All of the disks of eol-db-slave1 server shows green indicator but it reports that 4 disks missing from the disk group (RAID 10) after powering on, although the disks were reseated when the server is power off. We need to contact Dell. It could be hard disk controller issue, or something else. It looks like the controller could not see the 4 disks."

**Comment by jhammock** [comment]
Latest update from HEAT system:

2/8 Update:
Actually on eol-db-slave1, 4 disks were missing from Disk group. Called Dell support and he suggested to rebuild the disk group which may cause some data lost. After the conference call with Jeremy, Carmen, Jun and Dell support, Dell support proceeded rebuilding the disk group. Currently it is under the process of rebuilding the disk group.

**Comment by jhammock** [comment]
This corresponds to HEAT ticket 01081788

**Comment by jhammock** [comment]
From Mary:

After the disk group was re-built on eol-db-slave1, Tom and I had to build the OS  on it – RHEL 7. Currently RHEL 7 on eol-db-slave1 is up running and will install other components tomorrow.

**Comment by jhammock** [comment]
From Mary:

It was the disk array rebuilt. I’m going to set up the iDRAC, according to the Dell support the server has iDRAC8 enterprise, then we can check if the controller firmware is out of date.

**Comment by jhammock** [comment]
From Mary: 

Here is the brief update for today:
1.       I set up iDRAC on eol-db-slave1 and it is working well
2.       From iDRAC, the server looked heathy and all components have green indicators.
3.       I installed chef on the new eol-db-slave1 and bootstrapped/configured/sync the node to the Chef server after removing the old one from Chef server.

Will do:
1.       Will talk to Jeremy about MySQL installation
2.       I got the firmware update from Dell. Tom and I tried to build a bootable ISO to USB to update the firmware, since the server does not have DVD, but the built bootable ISO does not work. We will try something else tomorrow.

**Comment by jhammock** [comment]
From Mary:

I figured out a way to do the comprehensive firmware updates including BIOs. It is running updates now and will take hours to complete. Please leave eol-db-slave1 alone. Once it completes, I’ll send out an email.

**Comment by jhammock** [comment]
From Mary: 

Today Tom and I work hard to set up Docker  through Chef cookbook on the new eol-db-slave1 (RHEL 7):
1.       Set up a test Linux server running RHEL 6 as a Chef node and configured it from Chef server.
2.       Ran Chef-client (executing cookbooks) on the RHEL 6 test server and found that Docker was not installed by Chef-client. After manually installing Docker package on the test server, Chef-client configured Docker and started it up.
3.       For RHEL 6, Docker was installed from EPEL repository, but for RHEL 7, Docker is in RHEL7 extra channel instead of EPEL repo. So Tom configured the SI Satellite server to include RHEL 7  Extra channel for EOL servers running RHEL7.
4.       SI Satellite server takes time to run synchronization. After the sync is done, we will continue to work on that.

Currently the EOL servers have no backup. If they have the backup, the recovery will be much faster and easier. I voiced my concerns several times and wanted to say it again. According to our backup engineer, there is no storage for the backup of EOL servers.

**Comment by jhammock** [comment]
From Mary:

Tom fixed the issue of SI Satellite Katello and the sync of RHEL 7 Extra Channel from Satellite for EOL servers completed this afternoon, After installing Docker, Mariadb etc. needed packages and fixing some permission issues,  chef-client ran through successfully. Currently Docker and Sensu-client are up and running. Now we hand over eol-db-slave1 to Jeremy for the mysql database deployment etc.  Please let us know if you need any help.

**Comment by JRice** [comment]
Slave1 finally passed the disk benchmark:

```
$ sysbench --test=fileio --file-total-size=150G --file-test-mode=rndrw --init-rng=on --max-time=300 --max-requests=0 run
sysbench 0.4.12:  multi-threaded system evaluation benchmark

Running the test with following options:
Number of threads: 1
Initializing random number generator from timer.


Extra file open flags: 0
128 files, 1.1719Gb each
150Gb total file size
Block size 16Kb
Number of random requests for random IO: 0
Read/Write ratio for combined random IO test: 1.50
Periodic FSYNC enabled, calling fsync() each 100 requests.
Calling fsync() at the end of test, Enabled.
Using synchronous I/O mode
Doing random r/w test
Threads started!
Time limit exceeded, exiting...
Done.

Operations performed:  1042520 Read, 695013 Write, 2224000 Other = 3961533 Total
Read 15.908Gb  Written 10.605Gb  Total transferred 26.513Gb  (90.496Mb/sec)
 5791.77 Requests/sec executed

Test execution summary:
    total time:                          300.0003s
    total number of events:              1737533
    total time taken by event execution: 228.9521
    per-request statistics:
         min:                                  0.00ms
         avg:                                  0.13ms
         max:                                 44.37ms
         approx.  95 percentile:               0.25ms

Threads fairness:
    events (avg/stddev):           1737533.0000/0.00
    execution time (avg/stddev):   228.9521/0.00
```

So, we have **90.496Mb/sec** on this machine, compared to the ~ 4.5Mb/sec on slave2. ...So the disk here is, at least in a benchmark, about 20 times faster. ...Would be nice if that translated to superior mysql performance (but that doesn't appear to be the case in use.... which is curious.)
