### ISSUE TITLE
[8] Set up Tramea environment 

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#156]

**Comment by KamalMicheal** [comment]
This needs to be very simple. we need to remove the current entry barriers for developers installing the current EOL codebase. The vagrant was good. However, it needed some customization. 

I used to work on Virtualbox, having windows as a host, and Ubuntu as guest.
- having the work folder on the host, not the guest. this allows developers to use their preferred IDE on their host.
- port forwarding for the following:

`<Forwarding name="mysql" proto="1" hostip="127.0.0.1" hostport="3307" guestip="10.0.2.15" guestport="3306"/>
<Forwarding name="rails" proto="1" hostip="127.0.0.1" hostport="3000" guestip="10.0.2.15" guestport="3000"/>
<Forwarding name="solr" proto="1" hostip="127.0.0.1" hostport="8988" guestip="10.0.2.15" guestport="8988"/>
<Forwarding name="solr2" proto="1" hostip="127.0.0.1" hostport="8983" guestip="10.0.2.15" guestport="8983"/>
<Forwarding name="solr_test" proto="1" hostip="127.0.0.1" hostport="8989" guestip="10.0.2.15" guestport="8989"/>
<Forwarding name="ssh" proto="1" hostip="127.0.0.1" hostport="2202" guestip="10.0.2.15" guestport="22"/>`

Now you can access website, solr, solr test, mysql, and ssh from host.

**Comment by JRice** [comment]
...Do we know which connections we'll need for Tramea? For example, we're still not sure if we're using neo4j, Virtuoso (I hope not) or some other triple store (or none at all)... Nor resque/redis... or if we're going to have any new/novel technologies (you've mentioned Fedora)...

I just wonder if this might be a premature problem to solve, since we don't really have a Tramea environment to set up, yet. (?)

**Comment by AmrMMorad** [comment]
@JRice this can be considered initial task. It is mainly for installing the needed ruby and rails versions. This will help us working on the other Tramea tasks which don't depend on triplestores and this stuff.

**Comment by AmrMMorad** [comment]
latest ruby and rails (4.2.5) versions were installed successfully. Also installed latest mysql (5.7). I did a test by generating a scaffold and everything worked properly.

**Comment by JRice** [comment]
Does this involve creating a publicly-available git repository? (Or re-using the existing one?) Are we sure we want to use MySQL? The latest version of RHEL used at the SI suggests that everyone should move to MariaDB. Does this task involve setting up some kind of connection to VirtualBox, as Kamal suggests? If so, is this what we expect all developers to be doing?

**Comment by AmrMMorad** [comment]
We think this task will be "incremental" one. This can be changed according to our needs. The listed above are what we've done till now (definitely not the final environment). 

> Does this involve creating a publicly-available git repository? (Or re-using the existing one?) 

We think we need new repository separated from the current one specially that we have different ruby and rails versions.

> Are we sure we want to use MySQL? The latest version of RHEL used at the SI suggests that everyone should move to MariaDB.

In fact I found debate to determine which one is better. I remember that we've done a task before to investigate Maria DB. I guess Dima did a test for the current eol DB using Maria. 
If we are intending to use it, I think we need to compare between them according to our needs specially that I've read that one of the drawbacks of Maria is handling concurrent queries (without cache).
https://www.softizy.com/blog/mariadb-10-1-mysql-5-7-performances-ibm-power-8/
http://www.theregister.co.uk/2014/04/02/mysql_release/

> Does this task involve setting up some kind of connection to VirtualBox, as Kamal suggests? 

we are intending to work on remote machines as we are doing currently. We think this will be easier given that we didn't face a lot of problems using this scheme.

> If so, is this what we expect all developers to be doing?

No, it is just a beginning that will help us work on some basic tramea tasks (such as generic notification module or visualization one). This gonna be changed according to our needs.

**Comment by JRice** [comment]
> We think this task will be "incremental" one.

It's strange to estimate a task without knowing it's scope.

> We think we need new repository separated from the current one specially that we have different ruby and rails versions.

I do think it belongs in a repo so people can look at it.

> I found debate to determine which one is better.

Indeed. I don't know the answer. That's kind of my point: we don't know what we're doing yet.

...That said, clearly you need a ticket to track progress on... stuff. I'll stop arguing the point now.

**Comment by JRice** [comment]
Could we perhaps break this up into more specific tasks, such as "install Solr Cloud" and "Create Git Repository" and the like?

Just curious.  ;)
