### ISSUE TITLE
TraitBank upload missing references and contributor info

### ISSUE THREAD

**Issue by diatomsRcool** [EOL/tramea#163]
Resource 969 for TraitBank was recently ingested, but the references and contributor info were left off. It may be an error in the way I set up the archive, but it may also be an error in upload.

**Comment by jhammock** [comment]
Found an error in the meta that may explain the missing references, no explanation yet for the missing contributor.

**Comment by diatomsRcool** [comment]
Should I change the file and try again?

**Comment by jhammock** [comment]
Yes, we can probably learn something from which problems remain. You're welcome to try the spreadsheet instead if you prefer. Let @JRice know when the new resource is ready; I'm not sure what the timing will be on harvest experiments the next few days. Thanks!

**Comment by JRice** [comment]
(Waiting on this; ready when the file is!)

**Comment by diatomsRcool** [comment]
I'm in Arizona for the rest of the week. Can it wait?

**Comment by jhammock** [comment]
Yup, we can proceed with other test resources in the meantime

**Comment by JRice** [comment]
Psssst: when will this be good to go?

**Comment by diatomsRcool** [comment]
I can make it good to go before I leave on Thurs.....if that is what you 
want.
a

On 2/23/2016 3:37 PM, Jeremy Rice wrote:

> Psssst: when will this be good to go?
> 
> —
> Reply to this email directly or view it on GitHub 
> https://github.com/EOL/tramea/issues/163#issuecomment-187891570.

## 

Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by JRice** [comment]
I'm not in any terrible rush, personally, but it would be great to close
the ticket. :)

**Comment by diatomsRcool** [comment]
I just uploaded the new archive. It seemed to quickly process. I got this message back "Content partner resource details successfully updated. Current status of resource data: Uploading."

**Comment by jhammock** [comment]
blocked by https://github.com/EOL/tramea/issues/187

**Comment by JRice** [comment]
I actually side-stepped that problem, so the resource will be re-harvested today.

Anne won't be able to upload another with without #187 ... or with manual intervention.

**Comment by diatomsRcool** [comment]
So has this been reharvested? Should I see a difference?

**Comment by diatomsRcool** [comment]
I noticed another bit of weirdness, if we want to deal with it in this ticket.

**Comment by JRice** [comment]
It has been re-harvested. (I'm not sure what changed, so I can't tell you what would be different.) If you're seeing weirdness, you should report on it!  :)

**Comment by diatomsRcool** [comment]
The references and contributor info are still missing.

**Comment by diatomsRcool** [comment]
I added this https://github.com/EOL/tramea/issues/198 for the other weirdness, but I don't see how to add watchers or assignees.

**Comment by jhammock** [comment]
Also MeasurementRemarks and all Occurrence file metadata are missing. Also, as far as I can tell, all metadata attached in the MeasurementOrFact file using measurementOfTaxon=False.

**Comment by jhammock** [comment]
Fixed, I think :)
