### ISSUE TITLE
Get new data format from SI and ingest them to virtuoso staging server

### ISSUE THREAD

**Issue by AmrMMorad** [EOL/tramea#166]
This task is for getting the data from the SI server added by Jeremy. This data then will be ingested in virtuoso staging server at Egypt so we can make new traitbank tasks easier.

**Comment by jhammock** [comment]
Thanks for the ticket, Amr! This is a bug?

**Comment by AmrMMorad** [comment]
Actually this ticket may not be considered a bug , but it isn't estimable specially that this includes meetings and discussions with our sysadmins.
Thanks a lot

**Comment by jhammock** [comment]
Ah, in support of https://github.com/EOL/tramea/issues/156, I expect? Good luck!

**Comment by AmrMMorad** [comment]
Actually it is mainly for the new data format tasks.
Also I've added some tables' data in our mysql staging server to get this to work locally. Currently we have  data in the new format on our staging server.
