### ISSUE TITLE
[5] Add 9 new languages to names/common names/add a new name drop-down menu

### ISSUE THREAD

**Issue by BobCorrigan** [EOL/tramea#167]
Following up on a request from an EOL user:

> The following message was submitted to EOL via the Contact Us form:
> From: Megan Wannarka
> E-mail: m.wannarka@gmail.com
> Subject: Curator support
> 
> Hi-
> I'm wondering if you can add a few more language options. I served as a Peace Corps volunteer in Senegal, West Africa and have some local common names in Wolof (already listed), Sereer, Mandinka, Fulakunda, Pular, Pulla Fuuta, and Bambara If it's possible to add these to the list.
> 
> Also currently I'm working in the Eastern Caribbean. There are a few distinct languages here (Caribbean Kreyol/Kreol (different from French Creole), Patois/Patwa, and Grenadan dialect. I have 2 books with local names in them and many more from locals I would love to add to the database.
> 
> Is it possible to add these to the list?
> 
> Thank you
> 
> http://eol.org/users/100897

After consulting with the user, I have confirmed that she wants to add common names to EOL but in order to do so a number of language names need to be added to the drop-down menu found on the 
Taxon page > Names tab > Common Names sub-tab > Add a new name dialog

(example http://eol.org/pages/1037747/names/common_names)

The list of language names requested is as follows (please add them "as written"):

St. Lucian Kweyol
Grenadian English Creole
Grenadian French Creole
Sereer
Mandinka
Fulakunda/Fulani
Pular
Pulla Fuuta
Bambara

I will own communicating the status of this request with the user.  For the record her contact information is:

> Megan Wannarka
> Peace Corps Response Grenada
> Beekeeping Trainer/Specialist
> cell/whatsapp: 473-419-6987
> m.wannarka@gmail.com

**Comment by BobCorrigan** [comment]
When this is added to an iteration, if it is possible to safely push this to production prior to a deploy, I would appreciate finding out so I can stay on top of informing the user of its status.

**Comment by menna-hedaia** [comment]
To add these languages I need their iso 639 codes  . So could you send them to me ?
Thanks

**Comment by jhammock** [comment]
Good point. Only Bambara seems to have one. @BobCorrigan , perhaps the requesting user can help us?

**Comment by JRice** [comment]
https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes

...Might help, not sure.

**Comment by jhammock** [comment]
@menna-hedaia, we are thinking of creating substitute codes for some of these languages, as getting them added to the ISO might be elaborate advocacy work. _If_ using non- ISO codes won't break anything, can you tell me what other fields I should provide you along with the codes? Thanks!

**Comment by JRice** [comment]
They should have ISO 639-3 codes, which we can ... use... kinda.

St. Lucian Kweyol: **acf**
Grenadian English Creole: **gcl**
Grenadian French Creole: (there is none, so we might use **gcl-FR**, which isn't legal, but hey...)
Sereer: **srr**
Mandinka: **mnk**
Fulakunda/Fulani: **ff** (that's ISO-639-1, which is fine.)
Pular: **fuf**
Pulla Fuuta: (none, suggest **fuf-FF** because "ff" is Fuuta, if I understand correctly... I might not..)
Bambara: **bm** (639-1)

Sorry. I'm a linguist. I had to look.

**Comment by menna-hedaia** [comment]
@jhammock non-ISO codes wont break anything , we just need to have a unique ISO 639-1 code for every language.
@JRice I will use them , thankyou for looking

**Comment by menna-hedaia** [comment]
All languages need a unique ISO 639-1 codes , ISO 639-3 codes are not enough, so what are your suggestions regarding this, shall we create our own from the ISO 639-3 codes ?

**Comment by JRice** [comment]
Yes, as you said earlier, what we _call_ iso_639_1 doesn't actually _need_ to be ISO 639-1, it really just needs to be unique. The codes I gave you aren't actually valid (the code after the "-" is actualy reserved for difference in _script_ within the same language, not subgroups of related languages), but it really does just need to be unique for our purposes.

This isn't "the right thing to do" ...The right thing to do is to switch the entire application to use ISO-639-3, change harvesting to port older codes to ISO-639-3, and add provisional codes for languages not covered by ISO-639-3. But that is a LOT of work which we should reserve for Tramea. :D

**Comment by menna-hedaia** [comment]
Done. The 9 languages are added. The code for this is in the following branch 
https://github.com/EOL/eol/commit/2e30eae3f4ead2923d08711fdce4b69ab6e8b4d1

**Comment by jhammock** [comment]
Is this ready to merge to master?

**Comment by menna-hedaia** [comment]
Yes, this is merged.

**Comment by jhammock** [comment]
"AddNewLanguagesToCommonNames" has been released, but I'm not seeing the new names in the Language menu at http://eol.org/pages/1049561/names/common_names, for instance. Could you have a look, please, @menna-hedaia ? Thanks

**Comment by menna-hedaia** [comment]
Its working now and the languages are visible

**Comment by jhammock** [comment]
Nice!
