### ISSUE TITLE
[8] Investigate CMS plugins

### ISSUE THREAD

**Issue by AmrMMorad** [EOL/tramea#169]
This task is used to investigate the CMS plugins that can be used for TRAMEA

**Comment by AmrMMorad** [comment]
This issue includes demo for how to create a cms page from the current existed in EOL

**Comment by JRice** [comment]
Some "gems" to consider (though I'm sure you will find these in your travels):
- [Refinery](http://www.refinerycms.com/)
- [Locomotive](http://locomotive.works/)
- [BrowserCMS](http://www.browsercms.org/)

But, IM(H)O, we **really** need to consider using WordPress as a CMS. It's popular, _very_ well-documented, stable, and powerful. ...I don't know much about doing it, but you can find [lots about it on the web](https://managewp.com/wordpress-content-management-complete-guide), and I believe we should dedicate some of the time of this ticket to investigating the feasibility of using it for EOL. ([Here's someone talking](http://stackoverflow.com/questions/9277531/ruby-on-rails-integration-with-wordpress) about specifically doing it with Rails.)

It's a (serious) downside that it uses PHP, but it's pretty modern PHP and I don't think that's prohibitive (though it _is_ a serious strike against it).

**Comment by JRice** [comment]
ALSO, we should REALLY be talking to the rest of the team about this! THEY will be the ones using it... specifically the folks at SPG and L&E (mostly the latter, as I understand it). Tracy Barbaro'a opinion should carry _significant_ weight on this ticket.

**Comment by BobCorrigan** [comment]
When considering the different CMS, please make note of:
1. Is it "mobile-friendly"?
2. Is it responsive?
3. Does it offer SEO keyword management?
4. Can it be integrated into the rest of the EOL website experience with minimal disruption?
5. Does it accommodate users with disabilities?
6. Is it open source or commercial?  (We'd prefer to use an open source/free system)

In addition, I will be looking closely to see how we will integrate any CMS we choose with collections and other widgets/services for purposes of delivering EOL Places in Tramea.

Here are a few good recent reviews:

https://firebearstudio.com/blog/best-ruby-on-rails-content-management-systems-cms.html
http://www.railscarma.com/blog/technical-articles/5-best-ruby-on-rails-content-management-systems-cms/

FWIW, SI has standardized on Drupal.

**Comment by JRice** [comment]
Note: Refinery has i18n plugin: https://github.com/parndt/refinerycms-i18n

...This is important. We should consider this an important feature of any CMS we choose.

**Comment by BobCorrigan** [comment]
I would be Very Interested in hearing about the conclusions of this ticket, @jhammock

**Comment by menna-hedaia** [comment]
Multiple CMS gems were investigated these include:
1- RefineryCMS : This gem was found to be the most suitable , it supports recent versions of Rails, it is user-friendly, highly extensible , configurable and has an active community.
2- BrowserCMS : It doesnt support recent rails versions 
3- LocomotiveCMS : It supports MongoDb whereas we need MySQL , in the recent version editing sites is done using a command line tool called wagon , and hence is not suitable for non-technical users (only old versions have editing using text editors).
4- Comfortable Mexican Sofa : Very less functionalities and not user-friendly.
Moreover, as it can be seen here [https://www.ruby-toolbox.com/categories/content_management_systems], refinerycms is considered the most popular.
Please let me know if more information is needed.
Thanks
