### ISSUE TITLE
[5] Database design for user model, and review

### ISSUE THREAD

**Issue by AmrMMorad** [EOL/tramea#170]

**Comment by JRice** [comment]
I **strongly** suggest we use a Rails gem for the bulk of authentication. IMO, it was a **huge** mistake for us to "roll our own" user auth in Rails for EOL, and resulted in a lot of code which was _very_ difficult to follow, failed often, was difficult to extend, and cluttered controllers.

A [quick scan for what people are using](http://stackoverflow.com/questions/21904701/ruby-on-rails-4-what-authentication-gem-to-use) "these days" suggests that the [Devise gem](https://github.com/plataformatec/devise) is still quite popular, as is [OmniAuth](https://github.com/intridea/omniauth). (These are two gems which have been around for a long time in the Rails community.) [Here's one guide to using them](https://www.digitalocean.com/community/tutorials/how-to-configure-devise-and-omniauth-for-your-rails-application).

I'm going to _very strongly_ recommend we base our User model on these two gems... or spend a little time (a few hours at most) researching alternatives, if these make you uncomfortable. But they are staples and will greatly simplify our lives, including code maintenance, going forward.

**Comment by AmrMMorad** [comment]
Kindly find attached a document with the proposed design for user model.
[Uploading Users DB design.pdf…]()

**Comment by JRice** [comment]
We can get rid of the `admin_notes` field.
