### ISSUE TITLE
[1] Dynamic hierarchy discussion 

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#181]
To be scheduled with @katjaschulz and BibAlex team

**Comment by KatjaSchulz** [comment]
When would be a good time for the BibAlex team to do this?

**Comment by JRice** [comment]
Oops, I fear a pre-Harvard-meeting window has been missed: their day is over today and they don't work tomorrow. ...And Monday morning we're supposed to be estimating.  :S

They do work Sunday. ...Are you willing to meet (early) on Sunday?  If so, I'd suggest sending an email now asking them to meet then.  :S

**Comment by KatjaSchulz** [comment]
Generally, I am willing to meet on a Sunday, but not THIS Sunday.  I'm seriously exhausted after two weeks of travel and need a weekend off before I head out to yet another meeting.

**Comment by JRice** [comment]
Indeed! Okay, then we missed our chance this iteration. Given the amount of time you've been away, I don't think that's surprising.

Good luck resting! See you when you travel again next week! :-\

**Comment by AmrMMorad** [comment]
Thanks, Katja, for your time. That was helpful meeting.
