### ISSUE TITLE
[2] Discuss things to share at Feb 23 meeting with stakeholders

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#182]

**Comment by jhammock** [comment]
@YoustinaAtef @menna-hedaia @AmrMMorad @HudaSoliman Please plan this time to best meet your needs; things it would be helpful for stakeholders to bear in mind and/or things you need them to tell you. After this discussion, please let Jen know if you prefer a 3-3:30pm time slot or a longer one. We will adjust the rest of the day's agenda accordingly.

**Comment by mariestuder** [comment]
@YoustinaAtef @menna-hedaia @AmrMMorad @HudaSoliman  Looking forward to having you join the start of our meeting next week! Our agenda is flexible, so please feel free to request the time you need.

**Comment by AmrMMorad** [comment]
Sorry for late reply,
We think that 3 pm Alexandria time (we believe it is 8:00 AM ET) will be the most suitable for us.
@jhammock: If this will be at 3:00 PM, what about the sprint meeting?

**Comment by jhammock** [comment]
Sorry for the confusion, all! I was an hour off. I should have said 4-4:30, immediately after the regular (if compressed) sprint meeting. That would be a half hour session. An hour would also be fine for the stakeholders; I believe that's up against the end of work day for at least some of the BibAlex team, though.

**Comment by AmrMMorad** [comment]
Ok then I guess 4 (Alexandria time, right after the Sprint meeting) would be fine.
Thanks

**Comment by mariestuder** [comment]
Thank you Amr for clarifying that this time works. We are very much looking forward to having the BA team (or those who can make it) at the start of our meeting!
