### ISSUE TITLE
Set up Tramea environment: Solr Cloud installation

### ISSUE THREAD

**Issue by AmrMMorad** [EOL/tramea#183]
This is subissue from #156 
This issue is for installing solrcloud on tramea environment

**Comment by AmrMMorad** [comment]
I used the following gems for solr installations:
- Sunspot_rails which will enable us to use solr via sunspot.
- For solr cloud installation, I used gem sunspot_solr in development group in Gemfile. This represents a packaged distribution of solr for use with the Sunspot and sunspot rails gems.

**Comment by JRice** [comment]
YAAAAAAAAA-A-A-A-A-A-AYYYYY!!!

(I have been **dying** to use Sunspot for EOL since ... since... since ...
as long as I can remember!)
