### ISSUE TITLE
AmphibiaWeb connector problem

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#184]
see: http://eol.org/content_partners/7/resources/21

From @JRice preliminary investigation

Okay, so the error definitely came from SchemaValidator::validate
(This is an XML resource.)

Early guess: utf-8 is the problem; this COULD be a serious problem with PHP on that machine (the XML parser could choke on it), or it could be a quick case of changing a string somewhere, or it could be the file isn't saved properly in some way.

"Input Conversion" is actually an appropriate error.
The problem is (at least) a recurring character which vim renders as �~@
(If I remove those, it validates.)
I THINK it's an endash... e.g.:
Development: The eggs are laid in a small hemispherical mass of
jelly, 3�~@"4 cm in diameter. The egg mass contains only 8�~@"10 yellow eggs with a diameter of 2 mm
The quotes there really are quotes (meaning, they appear in the file as `&quot;`, so it is NOT part of the weird string), which is ... odd. Could be a connector problem...

Ahhh, I see: � means "Unicode character follows"

...I think that `&quot;` is SUPPOSED to be a quote!
...And that's making the UTF-8 invalid.
So some regex in the connector is probably replacing all "s with `&quot;`, which is screwing up multibyte characters. The regex needs to have a look-behind to check that the � isn't within three or four characters before the quote ... or it needs to be UTF-8 aware in general.
Tricksy.

I'm trying to fix it using regex in vim, but it looks like it might be more complicated than I thought. For posterity, the regex I used was `%s/\(\%ue2.\)\@<=&quot;/"/g`

It may not be restricted to dashes, I think is the problem...

**Comment by JRice** [comment]
Hey, Eli. Sorry, this is a tricky one.

What I did was to create a tiny PHP script in /eol on the harvest machine, called "foo.php". I then copied in the resource file locally as "foo.xml". The script reads the XML and it allows me to change things and see if the file is valid or not. FWIW, the error I was getting was:

```
Fatal Error 6003: input conversion failed due to input error, bytes 0xE2 0x80 0x26 0x71 on line 0\nFatal Error 6003: input conversion failed due to input error, bytes 0xE2 0x80 0x26 0x71 on line 0\nError 1544: encoder error on line 0
```

The first thing I did was to reduce the size of the file until I located the problem... I deleted half of the "taxon" nodes at a time until I found the problem; then I made sure there was ONLY one node in the file that I could delete to make it parse and leave in to make it fail. ...That's what revealed the problem. ...To fix the problem that I saw (the quotes as describe above), I used that regex above... but that's Vim-specific regex syntax. In a "normal" regex, it might look like `s/(?<\%ue2.)&quot;/"/g`.

...That fixed ONE error, but found another:

```
Fatal Error 6003: input conversion failed due to input error, bytes 0xE2 0x80 0x22 0x34 on line 0\nFatal Error 6003: input conversion failed due to input error, bytes 0xE2 0x80 0x22 0x34 on line 0\nError 1544: encoder error on line 0
```

(Note how the bytes have changed.)  So there's _another_ problem in there somewhere. I was going to start deleting half of the taxon nodes again to isolate the problem (again), etc, etc... but Jen stopped me.  ;)

I hope this helps; it's definitely a challenging problem.

**Comment by jhammock** [comment]
Hey, @eliagbayani . No great rush here, but when you're satisfied this is working, don't let me forget to update the [harvest queue](https://github.com/EOL/tramea/issues/186)

**Comment by eliagbayani** [comment]
Hi @jhammock ,
- http://eol.org/content_partners/7/resources/21
  Uploaded resource, and message said to be VALIDATED. Then I set it to force-harvest.

**Comment by eliagbayani** [comment]
[Another AmphibiaWeb issue](https://github.com/EOL/eol_php_code/issues/152)
