### ISSUE TITLE
more collections than expected after harvest

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#188]
Two extra collections connected with the Feller resource seem to exist now. One, judging by its collection ID and # of taxa, is the previous harvest, currently listed on the resource page as a preview harvest:

http://eol.org/content_partners/494/resources/958

The other extra collection I can’t figure out, though I suppose it may be the result of another earlier harvest: http://eol.org/collections/122408

Possibly a failure to unpublished/erase/substract previous harvests?

At first glance, the taxa in all three are mapped ok, and all three were last updated at the same time, ~7 hours ago.

**Comment by JRice** [comment]
I think I've found the problem, and I think I've fixed it, but it won't take effect until the next harvest. That said, the last few harvests (Moorea Biocode, Gymnodiniales) seem fine. ...from my perspective, anyway.

I could juggle the collections on Feller (and other recently-published resources), but I worry about doing that without fully understanding what happened.

We could re-harvest Feller and see what happens. ...Is this desirable?

**Comment by jhammock** [comment]
If you feel reharvesting would be a good test, sure. The extra collections are hard to detect and not bothering the owner.

**Comment by JRice** [comment]
I don't, actually—I expect this will come up again, if it's not resolved.

**Comment by jhammock** [comment]
This may be related or it may be a new issue. Duplicate taxa from the new resources, http://eol.org/content_partners/586/resources/553

For instance:

http://eol.org/pages/45525753/overview AND http://eol.org/pages/33307988/overview
http://eol.org/pages/45525755/overview AND http://eol.org/pages/33307990/overview

Failure of taxon merging seems less likely than failure of recognition/removal of last harvest's products. There are successfully merged taxa in the new resources also. The duplicates I've found all seem to be from the same name in subsequent harvests of the same resource. The older taxon page also seems to behave in an unusual way. I'm not sure how it looks in the database, but it shows in the [search results](http://eol.org/search?q=Eustrongylosoma+liklik&show_all=true). The older page lists the taxon name as "alternative name", and doesn't seem to have a primary name.

I could not find any duplicate collections, as originally observed in this issue.
