### ISSUE TITLE
OAuth login broken for Google

### ISSUE THREAD

**Issue by BobCorrigan** [EOL/tramea#190]
When I use EOL, I normally log in using my Google credentials. 

Today, when I attempted to do so, I got this message:
400. That’s an error.

Error: redirect_uri_mismatch

Application: Encyclopedia of Life

You can email the developer of this application at: lswalley@gmail.com

The redirect URI in the request: http://www.eol.org/login?oauth_provider=google did not match a registered redirect URI.

Learn more

Request Details
scope=https://www.googleapis.com/auth/userinfo.profile https://www.googleapis.com/auth/userinfo.email
response_type=code
redirect_uri=http://www.eol.org/login?oauth_provider=google
client_id=299568938175.apps.googleusercontent.com
That’s all we know.

(link https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=299568938175.apps.googleusercontent.com&scope=https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.profile+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email&redirect_uri=http%3A%2F%2Fwww.eol.org%2Flogin%3Foauth_provider%3Dgoogle)

I'm not sure what changed in our system to break this, or if others are having the same problem.

I was able to successfully log in to EOL using my EOL credentials.

**Comment by JRice** [comment]
I'm guessing this is related to #132 ...we should have @menna-hedaia look into this.

**Comment by HudaSoliman** [comment]
I checked it yesterday, using http://www.eol.org/login?oauth_provider=google to login didn't work, but if we dropped the 'www' the link will work http://eol.org/login?oauth_provider=google.

**Comment by HudaSoliman** [comment]
I think both ways are working now.

**Comment by HudaSoliman** [comment]
a new bug is opened to solve the login using 'www' #201
