### ISSUE TITLE
[5] getting harvests to scale- test performance of "smaller queries method"

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#193]
Per @JRice, as the BHL harvest reached 587000 relationships... still under 1000sec / 1K:

As I consider it, I think the main problem with this algorithm is pagination... each page loads in just a few seconds when it starts, then much slower when it gets to page, say, 500. ...I wonder if I could just try writing smaller queries, rather than using pagination...

**Comment by JRice** [comment]
The problem was an O(n^2) problem where an entire array was being scanned every time an element was added to it. 

This is, of course, ridiculous: just use a hash.

Changing the code reduced the time to process BHL's 587000 relationships to about 10 minutes.

**Comment by BobCorrigan** [comment]
bravo
