### ISSUE TITLE
TraitBank upload missing data

### ISSUE THREAD

**Issue by diatomsRcool** [EOL/tramea#198]
This upload http://eol.org/collections/120496. Is missing some data. I'm not sure why. For example, there is a measurement called Cingulum Type http://eol.org/schema/terms/CingulumType is in the list of known URIs http://eol.org/known_uris?page=5, but is not in the glossary. The values are in the glossary. Is this an issue of needing to migrate URIs to the glossary from the known uris page?

**Comment by diatomsRcool** [comment]
Update: These data show up on some species pages, but not others. I can see it here http://eol.org/pages/38996136/data, but not here http://eol.org/pages/918959/data

**Comment by jhammock** [comment]
Hmm... @diatomsRcool , can you see a pattern in which records are present? 

http://eol.org/data_search?utf8=%E2%9C%93&attribute=http%3A%2F%2Feol.org%2Fschema%2Fterms%2FCingulumType&commit=Search

About how many are missing?

**Comment by diatomsRcool** [comment]
OK, so this is really weird. If you sort the collection by richness and
then go down the list, looking at species.....it looks like the ones higher
up on the list are missing traits. They all seem to have lots of cell
lengths and cell widths. When I get to G. flavum, I see some extra traits,
but not all and mostly cell lengths and cell widths. G. sulcatum appears to
be complete. G. paradoxum appears to be complete. I'm going to go back and
look at the original resource and see if I can find a pattern there.

On Tue, Mar 8, 2016 at 9:01 PM, Jen Hammock notifications@github.com
wrote:

> Hmm... @diatomsRcool https://github.com/diatomsRcool , can you see a
> pattern in which records are present?
> 
> http://eol.org/data_search?utf8=%E2%9C%93&attribute=http%3A%2F%2Feol.org%2Fschema%2Fterms%2FCingulumType&commit=Search
> 
> About how many are missing?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EOL/tramea/issues/198#issuecomment-194066344.

## 

Anne E. Thessen, Ph.D.

The Data Detektiv, Owner and Founder

Ronin Institute, Research Scholar

443-225-9185
