### ISSUE TITLE
Statistical method not showing in overview tab TraitBank records

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#199]
For example, body length on http://eol.org/pages/1177922/overview

**Comment by menna-hedaia** [comment]
Done. The solution for this bug is in the following branch
https://github.com/EOL/eol/commit/63a6504758e61bdec85b102044aa6085ecfaf6a7

**Comment by jhammock** [comment]
Speedy! Thanks :)

**Comment by menna-hedaia** [comment]
Thankyou :))

**Comment by JRice** [comment]
Merge to master?

Thanks!

**Comment by menna-hedaia** [comment]
Merged to master.
Thankyou
