### ISSUE TITLE
When merging taxa, remove the old taxon from site search

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#200]
for instance, http://eol.org/search?q=Eustrongylosoma+liklik&show_all=true

**Comment by jhammock** [comment]
fixed, see https://github.com/EOL/tramea/issues/211

**Comment by jhammock** [comment]
Oops, the search results fix isn't in yet. Overexcited, sorry

**Comment by JRice** [comment]
Added the code to fix this; shouldn't be a problem for future harvests. If there are taxa there now that are bothering you, let me know and I'll remove those manually, too.
