### ISSUE TITLE
Common name selections don't persist

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#202]
Two users (@jhammock and @hyanwong) could not select a preferred common name for http://eol.org/pages/214854/names/common_names
Some attempts to select a name returned the user to the same subtab, unchanged, no error message. 

@jhammock could select the IUCN Red List name, and after that, select the FishBase name, which previously did not work. This selection stuck for a minute or two, but 20 minutes later the selection had reverted to the original, the Unknown Provider name.

**Comment by AmrMMorad** [comment]
I've tried these scenarios on [eol](http://eol.org) and worked for me. May I ask you to recheck this?
Thanks

**Comment by jhammock** [comment]
I could not reproduce this problem today, either on the original page or on four random pages (below). I'll check again tomorrow to see if my selections (the name with the most providers in each case) persists. @hyanwong, did you see a pattern to this or other particular pages showing the problem? Thanks

**Comment by hyanwong** [comment]
No, just something I stumbled upon. Sorry. It seems to work for me now. Perhaps something simply to keep an eye on.

**Comment by jhammock** [comment]
OK, I'll close this for now, since we can't reproduce it. Thanks, @hyanwong for reporting, and @AmrMMorad for looking into it.
