### ISSUE TITLE
Identical taxon pages, identical content, different taxon IDs

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#211]
For instance, http://eol.org/pages/1049441/overview and http://eol.org/pages/2201694/overview

@hyanwong reports there are many others. This may be a failure to delete bug. If this is expected behavior, SPG may just need an explanation of why it's ok.

**Comment by JRice** [comment]
Oh, right, this isn't actually a case of duplicate taxa: they ARE the same taxa. They're just two valid URLs for the same thing.

That said, we could be redirecting the user (via http) to the lower ID in these cases (FWIW: when two taxa merge, we always always ALWAYS merge TO the lower ID). That would cause the URL to be the same, which is good, I suppose.

I wasn't privvy to why, but long ago, we chose not to do that. But hey, it's a bold new world!

**Comment by JRice** [comment]
Nope! I lie!

It turns out we have a method to redirect the user already, appropriately called `redirect_if_superceded`, which appears to be ... not working. I'll find out why.

**Comment by JRice** [comment]
Oh, I see why. My fault. Iiiiiinteresting. I'll fix it, sorry!

**Comment by JRice** [comment]
Fixed; already in production.
