### ISSUE TITLE
[1][JR] editors.eol.org should point to eol-archive:8080

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#213]

**Comment by eliagbayani** [comment]
This ticket is to have editors.eol.org be accessible via HTTP.
It is in this server where we will host:
- EoEarth wiki: 
- BHL Literature Editor Project

Both projects will initially be just for a couple of users.
Time needed: I think Jen/Katja will decide on this. My sense is, as soon as possible but of course depending on the priority of things.

I’m in the initial stages of setting up eol-archive to host these projects and this ticket is needed for me to continue setting up.

**Comment by KatjaSchulz** [comment]
Since Bob can make do with mockups for his April talk in London, this is not urgent.  We need to make sure not to forget about this, though.

**Comment by JRice** [comment]
Pending tasks:
- Update config files - **done**
- Update DNS - **done**
- Restart varnish - **will happen automatically on April 12th**

**Comment by eliagbayani** [comment]
Hi @JRice , I just realized I can now ping editors.eol.org.
I assume I can now continue work on eol-archive, that is installing 
- MediaWiki
- BHL Editor project., etc.
  Thanks.
