### ISSUE TITLE
Parents are missing from hierarchies on some pages

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#216]
For instance: http://eol.org/pages/180721/names

This has happened before; two relevant jira tickets are a [report of the latest instance](https://eol-jira.bibalex.org/browse/WEB-5994) (not much detail) and a "[self healing hierarchies idea](https://eol-jira.bibalex.org/browse/WEB-5912)" that I _think_ is related. It was requested by @JRice and implemented by @HudaSoliman. Details below for convenience.

Created:    26/Feb/15 7:22 AM

"It occurred to me that it would only be moderately difficult for hierarchies to detect when they are "broken" and fix themselves.
This does require a bit of work. First, we need a way to keep track of what's being reindexed. Create a model called HierarchyReindexing, which belongs_to a hierarchy, has timestamps for completed_at and started_at, and has the other usual timestamps. That's it. (Remember to add the has_many on hierarchy to hierarchy_reindexing, too.)
Next, replace the "ancestors" relationship on a hierarchy_entry with "flat_ancestors", and write a method called "ancestors" which performs a simple check:

``` ruby
class HierarchyEntry
  def ancestors
    ancestors = flat_ancestors
    hierarchy.reindex if ancestors.empty? and parent_id > 0
  end
end

class Hierarchy
  def reindex
    HierarchyReindex.enqueue(self) unless hierarchy_reindex.pending
  end
end

class HierarchyReindex
  @queue = 'notifications' # Not the best, but whatever.
  scope :pending, -> {completed_at: nil}
  def self.enqueue(which)
    Resque.enqueue(HierarchyReindex, id: which.id)
  end
  def self.perform(args)
    Rails.logger.error("HierarchyReindex: #{args.values.join(', ')}")
    if HierarchyReindex.exists?(args["id"])
        begin
          HierarchyReindex.find(args["id"]).run
        rescue => e
          Rails.logger.error "HierarchyReindex (#{args["id"]}) FAILED: "\
            " #{e.message}"
        end
    else
       Rails.logger.error "HierarchyReindex #{args["id"]} doesn't exist, skippped."
    end
  end
  def run
    start
    hierarchy.repopulate_flattened
    complete
  end
  def start
    update_attributes(started_at: Time.now)
    update_attributes(completed_at: nil)
  end
  def complete
    update_attributes(completed_at: Time.now)
  end
end
```

...Ideally it would do something more intelligent than just writing an error to the log when it fails, but that's not necessary for a first pass.
Of course, a large part of this task would be writing tests for all of the pieces.
Don't bother writing tests for repopulate_flattened, though: that's basically raw SQL and we don't want to bother testing that aspect of it."

Resolved:   07/May/15

I'm not sure how much this event has in common with that one; just providing any possible leads I could find.

**Comment by HudaSoliman** [comment]
I checked the database, The self-healing code has detected the bug in this hierarchy in 2015, BUT the fix for this hierarchy ( and other 308 hierarchies)  was  pending in a queue called 'hierarchy_reindexings' which has been changed to the 'notifications' queue in Resque in Jan 2016  and we lost those pending tasks from the old queue.

I enqueued them now in the 'notifications' queue and waiting for them to be fixed (hopefully!).
Sorry for the long technical explanation, but I had to explain what's happening.

**Comment by JRice** [comment]
Sweeet!  Great catch.  Thanks!

**Comment by JRice** [comment]
I'm not sure what's causing this, but it's getting worse and affects most hierarchies. I looked into the "healing" code, and it's quite old, so I replaced it with the new hierarchy indexer, which is _much_ faster (orders of magnitude).

Code used (I'm running it on tools1; I've stopped all other background operations):

``` ruby
> log/reflatten.log
nohup bundle exec rails runner -e production "
Resource.with_master {
  Resource.harvested.includes(:hierarchy).each { |resource|
    EOL.log(%Q{#{resource.title} (#{resource.id})}) ;
    h = resource.hierarchy ;
    EOL.log(%Q{Empty hierarchy!}) unless h ;
    next unless h ;
    e = h.hierarchy_entries.where(depth: 4).first ;
    EOL.log(%Q{Nothing deep enough to check!}) unless e ;
    EOL.log(%Q{Already OK.}) if e and e.ancestors.size == 4 ;
    next if e and e.ancestors.size == 4 ;
    h.try(:flatten)
  }
}
" > log/reflatten.log &
tail -f log/reflatten.log log/production.log
```

**Comment by jhammock** [comment]
Sampling suggests no hierarchies remain affected!

**Comment by jhammock** [comment]
Looks like this is back. Some pages more affected than others, eg: http://www.eol.org/pages/37807/names

On the original example page, four hierarchies are affected, which is, I think, the same number as before; not sure if it's the same hierarchies: http://eol.org/pages/180721/names

**note to Jen, curate 37807 when the parents are back**

**Comment by JRice** [comment]
Yeah, this has "self-healing" code, but it's currently stopped because Notifications is stopped.

I think it's safe to restart that queue, so I've done so. This should fix the trouble...

**Comment by jhammock** [comment]
The self healing code has caught up now, judging by the queues. I think perhaps it restored some but not all of the missing parent taxa, see for instance http://eol.org/pages/1642/names?all=1

**Comment by JRice** [comment]
Yeah, there's clearly a bug in that self-healing code check that I _thought_ I'd mentioned in a comment, but I don't see anymore: it was skipping things that were "already in the queue", but really weren't (the process had died). I'm going to have to do it "the right way"...

**Comment by JRice** [comment]
I see what happened: it's a slave-lag thing that caused the child process to die without running, which left a bunch of jobs LOOKING like they were "pending". Ugh, cleaning this up isn't quite so simple. Drat...

I'll do a hacky job and put in a TODO for cleanup.

**Comment by JRice** [comment]
Okay, fixed, pushed to prod... the remaining problems are being "healed" (it's fixing BOLD right now).

**Comment by jhammock** [comment]
reopening this as a flag that this problem is showing again, eg: http://eol.org/pages/209688/names?all=1

As of this writing, 303 jobs in Notifications queue; I expect the self healing code is waiting in there. Other queues are empty.
