### ISSUE TITLE
BHL images not displaying on taxon pages 

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#222]
Images fail to display even after reindexing the taxon page, and the taxon page is listed on the data object page: http://eol.org/data_objects/32778209

Previously harvested and curated BHL images also don't display, though they can be found in the worklist of the taxon page: 
http://eol.org/data_objects/32778810
http://eol.org/pages/1049602/worklist

**Comment by HudaSoliman** [comment]
Hi @jhammock, 
I just checked the objects &  found http://eol.org/data_objects/32778209 is present in all its associated taxa.  Same thing is for the other data object http://eol.org/data_objects/32778810 is found in the media of its taxon in:  http://eol.org/pages/1049602/media?page=6&sort_by=status&status%5B%5D=trusted&type%5B%5D=image&utf8=%E2%9C%93
Am I missing something here?

**Comment by jhammock** [comment]
Thanks for checking, Huda! You're quite right; I forgot to close this one yesterday.
