### ISSUE TITLE
[8] CMS Implementation

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#225]

**Comment by jhammock** [comment]
When this task is picked up, could a brief status description be provided here? @BobCorrigan has expessed curiosity about the outcome of https://github.com/EOL/tramea/issues/169

**Comment by menna-hedaia** [comment]
@BobCorrigan 
The progress is as follows:
I investigated multiple cms gems . The most suitable gem was refinery , it has the main features of creating, removing and editing pages using a rich text editor. The release date of a page has been added and shown in pages. Adding Links, uploading files and images are also available. 
It is easy to maintain and extend. 
So , If it is possible I would like to demonstrate this cms plugin in tomorrow 's iteration meeting Tuesday April 5th at 2:30pmAlexandria/8:30amDCBoston.
Thankyou
