### ISSUE TITLE
Unpublished taxa disrupt search

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#226]
It looks like we have unpublished taxa in the search index.

If you search for Orconectes texanus on EOL, you get 3 autocomplete search suggestions.  Clicking on the first or second of these leads to a "Sorry, you can't access unpublished taxon" error.  The third one is a published page: http://eol.org/pages/44315244/overview

We need to make sure unpublished taxa are not indexed for search.

**Comment by jhammock** [comment]
See https://github.com/EOL/tramea/issues/210
