### ISSUE TITLE
Prokaryote TraitBank data not showing up on taxon page

### ISSUE THREAD

**Issue by diatomsRcool** [EOL/tramea#237]
The [prokaryote data set](http://eol.org/content_partners/729/resources/899) was harvested and shows up in my EOL account, but the data itself doesn't appear on any taxon pages. I have checked the measurements and values and all appears to be in order. Jeremy says its not cached.

**Comment by JRice** [comment]
Relevant logs:

```
## 31-04:19:33.414(0.02) resource.rb:454#port_traits
## 31-04:19:33.417 resource_porter.rb:22#port
.. 31-04:19:35.191(1.77) Finding metadata for 0 traits...
.. 31-04:19:35.205(0.01) No data to insert, skipping.
## 31-04:19:35.205 Return from resource_porter.rb:40#port
```

...So looks like there was a problem getting the traits into the OLD TraitBank, since there was nothing to pull over. Hmmmn.

**Comment by JRice** [comment]
There's nothing in the harvest log for this resource, either. I'll suggest re-harvesting this (and manually watching it) to see what happened.

**Comment by JRice** [comment]
Given what happened today, I _suspect_ this is just a case of the resource not being re-downloaded.

**Comment by diatomsRcool** [comment]
Is this something I need to do?

On 4/11/2016 3:26 PM, Jeremy Rice wrote:

> Given what happened today, I /suspect/ this is just a case of the 
> resource not being re-downloaded.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/EOL/tramea/issues/237#issuecomment-208514722

## 

Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by JRice** [comment]
FWIW, I just re-downloaded this manually.

**Comment by JRice** [comment]
I'm not sure that worked. The resulting files are quite old. Perhaps that's expected, though; if so, this was a red herring.

```
-rw-r--r--   1 www-data www-data  2184 Jan 30  2015 meta.xml
-rw-r--r--   1 www-data www-data 81463 Jan 30  2015 prokaryote_measurement.txt
-rw-r--r--   1 www-data www-data   770 Jan 29  2015 prokaryote_occurrence.txt
-rw-r--r--   1 www-data www-data   141 Jan 29  2015 prokaryote_reference.txt
-rw-r--r--   1 www-data www-data  8763 Apr 13  2015 prokaryote_taxon.txt
```

**Comment by diatomsRcool** [comment]
yes, I haven't had to change the files in a while.
a

On 4/11/2016 3:30 PM, Jeremy Rice wrote:

> I'm not sure that worked. The resulting files are quite old. Perhaps 
> that's expected, though; if so, this was a red herring.
> 
> |-rw-r--r-- 1 www-data www-data 2184 Jan 30 2015 meta.xml -rw-r--r-- 1 
> www-data www-data 81463 Jan 30 2015 prokaryote_measurement.txt 
> -rw-r--r-- 1 www-data www-data 770 Jan 29 2015 
> prokaryote_occurrence.txt -rw-r--r-- 1 www-data www-data 141 Jan 29 
> 2015 prokaryote_reference.txt -rw-r--r-- 1 www-data www-data 8763 Apr 
> 13 2015 prokaryote_taxon.txt |
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub 
> https://github.com/EOL/tramea/issues/237#issuecomment-208516769

## 

Anne E. Thessen, Ph.D.
The Data Detektiv, Owner and Founder
Ronin Institute, Research Scholar
443.225.9185

**Comment by JRice** [comment]
Well, I just re-ran it, and, indeed, there were 0 traits to port. So something is still not connecting with the harvest.

I'll look later... just thought it was low-hanging fruit to re-try it now.

**Comment by JRice** [comment]
I think this is another case where the measurements file has values of `TRUE` for `http://eol.org/schema/measurementOfTaxon`, and it needed to be `true` (lowercase).

I recently added case-insensitivity to this code, so it should actually work if we harvest it again ... but it may also be worth changing it for posterity (though not necessary).
