### ISSUE TITLE
NCBI has too many published versions

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#24]
http://eol.org/pages/6385875/names as an example

**Comment by jhpoelen** [comment]
does this explain why http://eol.org/api/hierarchy_entries/1.0/50761435.json?common_names=false&synonyms=false&format=json take (for|n)ever to return?

**Comment by JRice** [comment]
Yes and no. It's failing because of the number of children... but there's an N+1 query problem in the API code. ...thanks for pointing that out... I will make a bug for it.

**Comment by JRice** [comment]
(It has 21,600 children!)

**Comment by JRice** [comment]
...Already fixed it. ...Sadly, this is another one of those "now we need to push it to production" situations.  :(

**Comment by jhpoelen** [comment]
@JRice thanks for your reply! 

two questions: 

when do you think this fix is available? 

Also, for my use case, I actually don't need the entire hierarchy, only the focal taxon (not its children). Is there a way to simply leave out the children to speed up the process?

**Comment by JRice** [comment]
Fix: I wish I could say. Given the state of EOL staffing-wise, we deploy when we can deploy, which is relatively rarely. :(  Could be two months, could be next week. I hate admitting that; just being brutally honest with myself. :\

No children: That is an excellent suggestion! But, no, you cannot do that. I could ticketize a change request, but that's not likely to be implemented anytime soon (on the scale of months), and it's likely to fall into the "features for the next version of EOL" bucket, to continue the brutal honestly.

Is it just this particular entry you need? If so, I can email you the result (it's quite long).

Aaaaactually, as I think of it... gimme a few minutes, let me see if I can cobble together a direct link to a NON production server that you could point to when you're desperate (YMMV)...

**Comment by JRice** [comment]
Update: no, sorry, I cannot do this easily. [sigh] I'll put it on the TODO list, though, could be useful in the future.

**Comment by jhpoelen** [comment]
Thanks for being honest! Just to give you some context: one of the GloBI data sources uses NCBI taxon ids (nice!) and last import took started Oct 7, 2014 10:38p and finished Oct 9, 2015 10:31a ~ 36 hours to resolve ~ 11k ncbi taxa. back of a napkin calculation, this boils down to about 12s per taxon. Hope this helps. If only I could get my hands on a full dump of the eol taxon database . . . ; )

related data source:
Schriml, L. M., Arze, C., Nadendla, S., Ganapathy, A., Felix, V., Mahurkar, A., … Hall, N. (2009). GeMInA, Genomic Metadata for Infectious Agents, a geospatial surveillance pathogen database. Nucleic Acids Research, 38(Database), D754–D764. doi:10.1093/nar/gkp832
![screen shot 2015-10-09 at 11 25 04 am](https://cloud.githubusercontent.com/assets/1084872/10402140/6f93307c-6e78-11e5-89ea-7a7901ca6222.png)

**Comment by JRice** [comment]
Heh. Yes. Yes indeed, data dumps are very much on the TODO list. The problem is, it takes _us_ a long time to compile the information in a digestible format!

It sounds absurd (resisting the urge to say "because it is"...), but it reflects the priorities of a very early EOL, which wasn't focused on speed and was very antagonistic to large data dumps. :(

All I can say publicly is "we are aware of the problem and are sacrificing our carpal tunnels to fix it."

**Comment by jhpoelen** [comment]
Thanks for clarifying: this makes a lot of sense to me. I imagine it is no easy task to manage such a large corpus of knowledge / data / code with a large user base within budget / manpower constraints. . . thanks for being patient with me.

**Comment by JRice** [comment]
FWIW, the API fix has been deployed. Your link should work now. ...It won't
be "fast" [rolls eyes], but it should actually finish...

Yay?

**Comment by jhpoelen** [comment]
A total Yay! I was able to retrieve http://eol.org/api/hierarchy_entries/1.0/50761435.json?common_names=false&synonyms=false&format=json . Thanks for letting me know about the fix.
