### ISSUE TITLE
MeasurementType terms should be allowed not to have a TOC value

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#248]
(for instance, in http://eol.org/known_uris/2626/edit, Life History and Behavior is selected)

Usually, there is at least one, but if there aren't any, normal behavior should result for this measurementType

**Comment by JRice** [comment]
The problem is almost certainly in `TraitSet#traits_by_category` which should handle "other" properly, but isn't. :S

**Comment by JRice** [comment]
Ooops, this was a half-baked feature in the code. Finished.
