### ISSUE TITLE
EOL front end should support Creative Commons licenses v. 4.0

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#249]
https://creativecommons.org/licenses/by/4.0/
https://creativecommons.org/licenses/by-sa/4.0/
https://creativecommons.org/licenses/by-nc/4.0/
https://creativecommons.org/licenses/by-nc-sa/4.0/

4.0 is the current version of the licenses. It does not render in object or taxon pages, eg: http://eol.org/data_objects/33099848

**Comment by AmrMMorad** [comment]
Done. Mainly images' links were missed in the database in addition to missing titles.
Thanks

**Comment by jhammock** [comment]
Beautiful, thanks!
