### ISSUE TITLE
Page parameter is ignored in Collections API

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#251]
@KatjaSchulz : I am experiencing a problem with the collections API that may be related to https://github.com/EOL/tramea/issues/148 or https://github.com/EOL/tramea/issues/39. When I try to access the items from a particular collection, I cannot get past page 1 of the API results, i.e., 
http://eol.org/api/collections/1.0/122675.xml?page=2&per_page=500&filter=&sort_by=alphabetical&sort_field=&cache_ttl=&language=en
gets me exactly the same results as
http://eol.org/api/collections/1.0/122675.xml?page=1&per_page=500&filter=&sort_by=alphabetical&sort_field=&cache_ttl=&language=en

The same happens when I ask for the json response. It looks like the page parameter is ignored.

**Comment by HudaSoliman** [comment]
There was a bug with caching the API queries
Fixed on this branch : https://github.com/EOL/eol/commit/68e4d7b57f21f4323d70ef48d64052eb94d97fac

**Comment by JRice** [comment]
Right! Thanks.

FWIW, I (manually) put this change on the (live) production servers, but this code should still be merged to master.

**Comment by jhammock** [comment]
Looks lovely, thanks!
