### ISSUE TITLE
"Could not find a data point" error

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#252]
eg: "Could not find a data point for http://eol.org/resources/692/measurements/b73beb1e85e67d3e84f3d0f5f2230c73"

This text found in place of a record, amid other intact records from the same resource,
on http://eol.org/pages/15024/data on April 7

**Comment by JRice** [comment]
I wrote a few methods to help: `Trait#make_point` will fix the problem once you find the trait, and you can do that with `PageTraits#pointless`. Something like this:

```
PageTraits.new(page_id).pointless.each { |t| t.make_point }
```

...We **do not** (!!!) want to call that on every page load! Please don't do that. Pretty please?

This ticket should be to figure out the best way to do this without harming the user experience.

**Comment by JRice** [comment]
This was actually ridiculously easy; I was over-thinking it. Done.
