### ISSUE TITLE
Resources with bad merges, for re-publication or Bad Merge Splitter Tool

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#254]
Remains of https://github.com/EOL/tramea/issues/220, but we have the tools to deal with it now :)

http://eol.org/content_partners/709/resources/799  There is an updated version of this resource uploaded, which could be harvested. Not until we're ready for a ~220k taxa harvest, though.

http://eol.org/content_partners/709/resources/804 No additional records to add, but this resource is also suffering from metadata not displaying (https://github.com/EOL/tramea/issues/253) which might call for a new harvest.

**Comment by millerse** [comment]
If I could add http://eol.org/content_partners/681/resources/961 to the list.  The verbatim depth is missing.

**Comment by jhammock** [comment]
https://github.com/EOL/tramea/issues/220 is still open, but the first batch of bad merges has been targeted and split.
