### ISSUE TITLE
Old format Public domain value of Rights field should display in data objects API

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#270]
I believe this value is simply the text string "public domain" in the media file field 
http://purl.org/dc/terms/rights

eg:
http://eol.org/data_objects/964156/

http://eol.org/api/data_objects/1.0/964156.json?taxonomy=false&cache_ttl=&language=en

**Comment by AmrMMorad** [comment]
In fact there were 3 data objects which have the same problem (964156, 964157, 964158). The data objects API returns the source url of the license. The source url for these objects was empty. I modified them to refer to a license which has string (Public Domain) source url.
I checked it now and returned "Public Domain" in the license field. Could you please check and let me know if there is a problem?
Thanks

**Comment by jhammock** [comment]
Oh wow- only three objects in our whole database? In that case I think we're good now. I thought there might be many more, if that string was a value we once supported. In any case, there should only be the currently supported urls in incoming content, so I think this is done. Thanks!
