### ISSUE TITLE
Remnants of unpublished Lily Database records hanging around in data tabs.

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#271]
I just noticed that there were a bunch of data records with "source missing" in the Acer rubrum data tab: http://eol.org/pages/582246/data
All of these show "See original source" instead of the content partner link.

It looks like all of these records are duplicates of records from the Shaw Nature Reserve data set aka Lily Database: http://eol.org/collections/104829

If I remember correctly, a duplicate of this dataset was published by accident a few weeks ago and then unpublished.  Apparently, the unpublication did not pull the data records from the data tab but rather orphaned them, also stripping all the metadata.  

These ghost records are also pulled up in the search interface, e.g., check out the search for "seed per unit:" http://eol.org/data_search?attribute=http%3A%2F%2Feol.org%2Fschema%2Fterms%2FSeedPerUnit&sort=desc
There's a ghost record for every single Shaw Nature Reserve record.

**Comment by JRice** [comment]
I _think_ I have cleaned these up. At least for this one resource. :S

it wasn't actually easy, but I did try to make it easier for the next time around... Let me know if there are others!
