### ISSUE TITLE
TB unopened rows, righthand links point to the wrong place

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#275]
For instance: http://eol.org/pages/5387764/data#data_point_3613539

The link in the upper right of this record, "USDA NRCS PLANTS Database", points to the resource page, http://eol.org/content_partners/36/resources/727. This page is not publicly viewable and will block the user with a weird "please log in" error.

Those links aught to point to the partner profile page, (in this case http://eol.org/content_partners/36), the same destination as the ones in the lower left for "Supplier", visible in an open TB row. This redundancy is intentional (though we may redesign in v3.)

**Comment by JRice** [comment]
Lamesauce.
