### ISSUE TITLE
The notifications queue may be stuck

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#279]
At least, it is slowly creeping upward right now, and the total length (>14,000) seems high. If I had been paying closer attention I'd have a better idea whether it has gone down at any point the past few weeks.

http://eol.org/admin

The queue may include tasks added as part of https://github.com/EOL/tramea/issues/216

**Comment by JRice** [comment]
It was stuck; it's free now, but it's now processing all of our splits (and then the notifications and cache-clearing that follow), so it's quite full. ...But it's running.
