### ISSUE TITLE
Missing delete link beside comments

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#28]
I vaguely remember this getting fixed, but something must have happened to that. :\

**Comment by AmrMMorad** [comment]
In fact I can see delete link beside comments in both EOL and my local server. Could you kindly please provide an example?

**Comment by JRice** [comment]
Not at e moment, but could you try as a curator and as an admin?

**Comment by AmrMMorad** [comment]
I tried as both admin and curator and still can see "delete" link. Also I reviewed its code and found that it is mainly checking for the "type" of the user; whether it is an admin or not...

**Comment by JRice** [comment]
Okay, thanks for checking. I seem to recall this was specific to Data
Object pages, but that's a vague recollection and I cannot find the
original ticket and I cannot find the email reminding me this is a problem,
so perhaps I just imagined the whole thing. Now the march of life is
missing, so I'm distracted enough that I don't care.

You may close this with a comment of "cannot reproduce". Thakns.
