### ISSUE TITLE
Tool to send TB download requests to the back of the data queue

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#286]
Large TB download requests can clog the data queue.

This is not a bug per se, but the right solution for now is probably a quick fix, so that if multiple large downloads are requested and cause a multi day delay, all but the current job can easily be sent back behind all smaller jobs, periodically until the backlog clears.

JR Edit:

The problem is we don't actually know the size of a request when it gets put in the queue (at the moment—we _could_ adjust the code to estimate the size based on the search query which built it).

As an alternative, we could implement a Buffet<sup>[1](#myfootnote1)</sup> approach:

```
When I pick up a job
  Scan the queue for other jobs from the same user
  Remove those jobs from the queue
  Re-add them at the end of the queue
```

This will have the effect of "all other users get a chance to get a download file before you get a second file."  This should be (mostly) adequate.

<a name="myfootnote1"><sup>1</sup></a> Meaning, you don't go back up for seconds until everyone else has gone through the line.

**Comment by HudaSoliman** [comment]
pushed to the master
