### ISSUE TITLE
Cannot edit a measurement type in the URI registry because it is not listed among Known URIs

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#287]
When I try to create a term with the following URI:
http://eol.org/schema/terms/VoucheredSequence
I get this error message:
1 validation error found
URI has already been taken

Problem is that this URI is nowhere to be found in the URL registry (http://eol.org/known_uris).  Jen and I both scoured all pages of measurement URIs (where this should be found) as well as the values, metadata, and even associations.  NADA.

So there seems to be a bug with not all known URIs being displayed in the Known URIs table.  

Actually, this brings up a feature request: if somebody tries to create a new URI but it matches an existing URI, it would be nice to provide the option to go strait to the form where the existing URI can be edited.

**Comment by JRice** [comment]
http://eol.org/known_uris/70149/edit

;)

**Comment by JRice** [comment]
(FWIW: we REALLY need a  search-by-uri interface there. It's really not _that_ hard to do, and a good candidate for a BA task.)

**Comment by KatjaSchulz** [comment]
Thx!
