### ISSUE TITLE
youtube videos not displaying

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#289]
Since our most recent harvest, Youtube videos are not displaying on EOL, though they are harvested. The data object pages contain an empty box, and Jeremy reports:

net::ERR_BLOCKED_BY_CLIENT

http://us-u.openx.net/w/1.0/sd?id=537072956&val=EVItREUCL0wJXClPEgA2RUACKEUJUCJJR1AmPsA-

Could you take a look when you have a little time, Eli? No great rush. The harvest queue isn't even re started yet.

**Comment by eliagbayani** [comment]
Problem is not with harvest or connector.
Anyway this is how we display in eol.org a video flash. It worked for the longest time but not anymore.

&lt; object data='http://www.youtube.com/embed/zrYBBjpjwx0' height='420' type='application/x-shockwave-flash' width='540' &gt;
…
…
&lt;/object&gt;

The quick fix is to remove the value (application/x-shockwave-flash) for attribute ‘type’ in &lt;object&gt; element. Like so:
&lt;object data='http://www.youtube.com/embed/zrYBBjpjwx0' height='420' type='' width='540'&gt;
…
…
&lt;/object&gt;
This will display the video just fine.

**Comment by jhammock** [comment]
Thanks for that advice, Eli! Hopefully someone can pick up this task shortly. A quick fix sounds great for right now. I guess we can also revisit video display in Tramea...

**Comment by JRice** [comment]
Hmmmn. I suppose this is worth some consideration; isn't Flash player dead, now? ...As in, unsupposted and insecure?

Definitely something to revisit. I'll try removing the type tag, though...

**Comment by JRice** [comment]
Looks like it worked. ...Might be best to check for regressions on all other video types (all media, really), but I'm going to move on for now...
