### ISSUE TITLE
newly created terms are not visible in the Known URIs interface

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#290]
eg:

http://eol.org/schema/terms/lowArctic

http://eol.org/schema/terms/highArctic

These should appear at the bottom of http://eol.org/known_uris?page=8&uri_type_id=3

(The top of the first page of http://eol.org/known_uris?page=1&uri_type_id=3 would also be fine, but prior behavior was for new terms to appear at the bottom of the last page)

**Comment by JRice** [comment]
Almost 100% (99.9%, anyway) sure this is slave lag.

**Comment by jhammock** [comment]
yup, there they are
