### ISSUE TITLE
adding an object to a collection does not work

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#305]
Reported by a user, Jen tested by trying to add http://eol.org/pages/581806/ to http://eol.org/collections/31138 and http://eol.org/collections/12611 by selecting both collections in the collect dialog box.

Response: "Sorry, there was an error; error." The object was added to neither collection.

neither [Jen's activity feed](http://eol.org/users/20470/activity?utf8=%E2%9C%93&filter=collections) nor [the reporting user's](http://eol.org/users/100897/activity?utf8=%E2%9C%93&filter=collections) mention the attempted action.

Still possibly slave lag?

**Comment by jhammock** [comment]
Correction: adding an object to a single collection results in the same error.

**Comment by JRice** [comment]
It turns out this is failing for the same reason adding data objects is failing... and probably a few other things: Solr isn't keeping up with write locks.

I'll fix this with a config change on Monday... though I'm also attempting to work around it in code, now...

**Comment by JRice** [comment]
Fixed.. ...for now...
