### ISSUE TITLE
Resource upload fails

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#319]
I just tried to create a new resource for EOL content partner number 178, but when I try to submit the resource form, I get the following error: 413 Request Entity Too Large

Here are the parameters I entered:

Resource name: MammalDIET
Original Data Source: http://dx.doi.org/10.5061/dryad.6cd0v
Upload resource file: spreadsheet from my computer
License: cc-zero
Bibliographic citation: Kissling, W.D., Dalby, L., Fløjgaard, C., Lenoir, J., Sandel., B., Sandom, C., Trøjelsgaard, K. & Svenning, J.-C.: Establishing macroecological trait datasets: digitalization, extrapolation, and validation of diet preferences in terrestrial mammals worldwide. Ecology and Evolution DOI: 10.1002/ece3.1136.
Resource description: A comprehensive global dataset of diet preferences of mammals (‘MammalDIET’). Diet information was digitized from the literature and extrapolated for species with missing information. The original and extrapolated data cover species-level diet information for >99% of all terrestrial mammals.
Auto-publish

Everything else is the default.

I tried removing the Bibliographic citation and Resource description, but I still get the same error.

**Comment by jhammock** [comment]
Oops, never mind. Spreadsheet resources not working is known and worked around.

**Comment by KatjaSchulz** [comment]
Spreadsheet converter is now here: http://editors.eol.org/eol_php_code/applications/xls2dwca/
Use xls not xlsx, use dropbox link, change dl=0 to dl=1.  Sigh!
