### ISSUE TITLE
[1d] create collection fails when providing duplicate collection item ids

### ISSUE THREAD

**Issue by jhpoelen** [EOL/tramea#32]
Steps to reproduce:
1. create file `collections.json` with content below
2. create a collection using wapi using something like:
   `curl --verbose -X POST --header "Content-Type: application/json" --header 'Authorization: Token token=[api token] -d @collection.json eol.org/wapi/collections`

expected results: 
Collection is created, perhaps leaving out eol ids that no longer exist or are incorrect. If these is something wrong with the parameters, I would expect to see which parameter is wrong and how to correct it.

actual result:
"Collection create failed. Check if there is a problem in the passed parameters.". see curl logs below the collection json.

collection.json file:

``` js
{"collection":{"name":"my name","description":"my description","collection_items":[{"collected_item_type":"TaxonConcept","collected_item_id":915104},{"collected_item_type":"TaxonConcept","collected_item_id":1051309},{"collected_item_type":"TaxonConcept","collected_item_id":1051993},{"collected_item_type":"TaxonConcept","collected_item_id":1050872},{"collected_item_type":"TaxonConcept","collected_item_id":1049431},{"collected_item_type":"TaxonConcept","collected_item_id":1049439},{"collected_item_type":"TaxonConcept","collected_item_id":913186},{"collected_item_type":"TaxonConcept","collected_item_id":1052548},{"collected_item_type":"TaxonConcept","collected_item_id":1052079},{"collected_item_type":"TaxonConcept","collected_item_id":1052072},{"collected_item_type":"TaxonConcept","collected_item_id":1049471},{"collected_item_type":"TaxonConcept","collected_item_id":922655},{"collected_item_type":"TaxonConcept","collected_item_id":1046720},{"collected_item_type":"TaxonConcept","collected_item_id":1177531},{"collected_item_type":"TaxonConcept","collected_item_id":1052728},{"collected_item_type":"TaxonConcept","collected_item_id":1052768},{"collected_item_type":"TaxonConcept","collected_item_id":1049549},{"collected_item_type":"TaxonConcept","collected_item_id":1048993},{"collected_item_type":"TaxonConcept","collected_item_id":916843},{"collected_item_type":"TaxonConcept","collected_item_id":918920},{"collected_item_type":"TaxonConcept","collected_item_id":1049516},{"collected_item_type":"TaxonConcept","collected_item_id":1048953},{"collected_item_type":"TaxonConcept","collected_item_id":1051322},{"collected_item_type":"TaxonConcept","collected_item_id":1053023},{"collected_item_type":"TaxonConcept","collected_item_id":1048975},{"collected_item_type":"TaxonConcept","collected_item_id":1049164},{"collected_item_type":"TaxonConcept","collected_item_id":1049046},{"collected_item_type":"TaxonConcept","collected_item_id":1049581},{"collected_item_type":"TaxonConcept","collected_item_id":1049760},{"collected_item_type":"TaxonConcept","collected_item_id":1048978},{"collected_item_type":"TaxonConcept","collected_item_id":1048976},{"collected_item_type":"TaxonConcept","collected_item_id":1048977},{"collected_item_type":"TaxonConcept","collected_item_id":1048966},{"collected_item_type":"TaxonConcept","collected_item_id":1048973},{"collected_item_type":"TaxonConcept","collected_item_id":917151},{"collected_item_type":"TaxonConcept","collected_item_id":1051989},{"collected_item_type":"TaxonConcept","collected_item_id":1050919},{"collected_item_type":"TaxonConcept","collected_item_id":915655},{"collected_item_type":"TaxonConcept","collected_item_id":1049569},{"collected_item_type":"TaxonConcept","collected_item_id":1049773},{"collected_item_type":"TaxonConcept","collected_item_id":915489},{"collected_item_type":"TaxonConcept","collected_item_id":917154},{"collected_item_type":"TaxonConcept","collected_item_id":1050834},{"collected_item_type":"TaxonConcept","collected_item_id":918912},{"collected_item_type":"TaxonConcept","collected_item_id":918803},{"collected_item_type":"TaxonConcept","collected_item_id":1052592},{"collected_item_type":"TaxonConcept","collected_item_id":1049378},{"collected_item_type":"TaxonConcept","collected_item_id":1049563},{"collected_item_type":"TaxonConcept","collected_item_id":1049475},{"collected_item_type":"TaxonConcept","collected_item_id":1049366},{"collected_item_type":"TaxonConcept","collected_item_id":1049762},{"collected_item_type":"TaxonConcept","collected_item_id":1049002},{"collected_item_type":"TaxonConcept","collected_item_id":1048964},{"collected_item_type":"TaxonConcept","collected_item_id":1047342},{"collected_item_type":"TaxonConcept","collected_item_id":1047043},{"collected_item_type":"TaxonConcept","collected_item_id":1048566},{"collected_item_type":"TaxonConcept","collected_item_id":1177539},{"collected_item_type":"TaxonConcept","collected_item_id":922253},{"collected_item_type":"TaxonConcept","collected_item_id":922241},{"collected_item_type":"TaxonConcept","collected_item_id":1051310},{"collected_item_type":"TaxonConcept","collected_item_id":1177536},{"collected_item_type":"TaxonConcept","collected_item_id":10964109},{"collected_item_type":"TaxonConcept","collected_item_id":12120713},{"collected_item_type":"TaxonConcept","collected_item_id":1050633},{"collected_item_type":"TaxonConcept","collected_item_id":1052056},{"collected_item_type":"TaxonConcept","collected_item_id":1052017},{"collected_item_type":"TaxonConcept","collected_item_id":922693},{"collected_item_type":"TaxonConcept","collected_item_id":1052536},{"collected_item_type":"TaxonConcept","collected_item_id":1178577},{"collected_item_type":"TaxonConcept","collected_item_id":918159},{"collected_item_type":"TaxonConcept","collected_item_id":919946},{"collected_item_type":"TaxonConcept","collected_item_id":1178497},{"collected_item_type":"TaxonConcept","collected_item_id":922653},{"collected_item_type":"TaxonConcept","collected_item_id":1052763},{"collected_item_type":"TaxonConcept","collected_item_id":921034},{"collected_item_type":"TaxonConcept","collected_item_id":1052765},{"collected_item_type":"TaxonConcept","collected_item_id":921032},{"collected_item_type":"TaxonConcept","collected_item_id":1177485},{"collected_item_type":"TaxonConcept","collected_item_id":1177464},{"collected_item_type":"TaxonConcept","collected_item_id":1049187},{"collected_item_type":"TaxonConcept","collected_item_id":1049166},{"collected_item_type":"TaxonConcept","collected_item_id":1049123},{"collected_item_type":"TaxonConcept","collected_item_id":1049085},{"collected_item_type":"TaxonConcept","collected_item_id":1049024},{"collected_item_type":"TaxonConcept","collected_item_id":1050134},{"collected_item_type":"TaxonConcept","collected_item_id":1049549},{"collected_item_type":"TaxonConcept","collected_item_id":1048731},{"collected_item_type":"TaxonConcept","collected_item_id":1049546},{"collected_item_type":"TaxonConcept","collected_item_id":1049378},{"collected_item_type":"TaxonConcept","collected_item_id":1049551},{"collected_item_type":"TaxonConcept","collected_item_id":1049565},{"collected_item_type":"TaxonConcept","collected_item_id":1049547},{"collected_item_type":"TaxonConcept","collected_item_id":1049474},{"collected_item_type":"TaxonConcept","collected_item_id":1049518},{"collected_item_type":"TaxonConcept","collected_item_id":1049630},{"collected_item_type":"TaxonConcept","collected_item_id":1049333},{"collected_item_type":"TaxonConcept","collected_item_id":1049365},{"collected_item_type":"TaxonConcept","collected_item_id":1049342},{"collected_item_type":"TaxonConcept","collected_item_id":1049606},{"collected_item_type":"TaxonConcept","collected_item_id":1049342},{"collected_item_type":"TaxonConcept","collected_item_id":1045998},{"collected_item_type":"TaxonConcept","collected_item_id":1048999},{"collected_item_type":"TaxonConcept","collected_item_id":914528},{"collected_item_type":"TaxonConcept","collected_item_id":914551},{"collected_item_type":"TaxonConcept","collected_item_id":1047918},{"collected_item_type":"TaxonConcept","collected_item_id":1048951},{"collected_item_type":"TaxonConcept","collected_item_id":1048958},{"collected_item_type":"TaxonConcept","collected_item_id":1048943},{"collected_item_type":"TaxonConcept","collected_item_id":1049046}]}}
```

curl trace:

---

> POST /wapi/collections HTTP/1.1
> Host: eol.org
> User-Agent: curl/7.43.0
> Accept: _/_
> Content-Type: application/json
> Authorization: Token token=XXXXXXXXXXXXXXXX
> Content-Length: 7369
> Expect: 100-continue
> 
> < HTTP/1.1 100 Continue
> - We are completely uploaded and fine
>   < HTTP/1.1 200 OK
>   < Server: nginx/1.8.0
>   < Content-Type: application/json; charset=utf-8
>   < Status: 200 OK
>   < X-UA-Compatible: IE=Edge,chrome=1
>   < ETag: "3896733480aca83602457117b93f6d2b"
>   < Cache-Control: max-age=0, private, must-revalidate
>   < Set-Cookie: _eol_session=BAh7BkkiD3Nlc3Npb25faWQGOgZFRkkiJWQ4NzE4OGUzNTEyNGM3Yjg4YWNlYjk4ZTg4YmI3YzlmBjsAVA%3D%3D--cce4021cb2e00ef30cb0d8e811e0c45a520f2178; path=/; HttpOnly
>   < X-Request-Id: 15a0796f2047242419fba52d6cedbdc1
>   < X-Runtime: 18.124652
>   < X-Rack-Cache: invalidate, pass
>   < Content-Length: 81
>   < Accept-Ranges: bytes
>   < Date: Wed, 21 Oct 2015 02:34:29 GMT
>   < X-Varnish: 1775681210
>   < Age: 0
>   < Via: 1.1 varnish
>   < Connection: keep-alive
>   < 
> - Connection #0 to host eol.org left intact
>   "Collection create failed. Check if there is a problem in the passed parameters."

**Comment by jhpoelen** [comment]
update on this issue: I was able to reproduce this by saving a small list of items with duplicate ids. Please confirm that this is causing the request to fail.

**Comment by JRice** [comment]
Almost certainly, but that's time-consuming to programmatically assert. (we
will eventually, but ATM I'm inclined to say "that's the problem")

I totally agree that we are not reporting errors correctly (one of the
reasons I didn't want to leak that this wapi existed to others, sigh), will
put that on the TODO list...

(example: also nice to report whether you cannot edit the collection because you don't have write access... and any other "easy" catches for validation errors... like a malformed collection_item_type)

**Comment by YoustinaAtef** [comment]
I concatenated a case specific error message to the originally existed one in create and update funtions.
You can find it under this branch https://github.com/EOL/eol/compare/%2332

**Comment by jhpoelen** [comment]
Thank you all for having a look at this so quickly. For some reason I didn't see the new and improved error messages (see log below). Could it be that the fix is not yet deployed?

---

$ curl --verbose -X POST --header "Content-Type: application/json" --header "Authorization: Token token=XXXX" -d @collection.json eol.org/wapi/collections
-   Trying 160.111.248.28...
- Connected to eol.org (160.111.248.28) port 80 (#0)
  > POST /wapi/collections HTTP/1.1
  > Host: eol.org
  > User-Agent: curl/7.43.0
  > Accept: _/_
  > Content-Type: application/json
  > Authorization: Token token=fa1fe503868a7390988770f13e6ade5398f15563
  > Content-Length: 7369
  > Expect: 100-continue
  > 
  < HTTP/1.1 100 Continue
- We are completely uploaded and fine
  < HTTP/1.1 200 OK
  < Server: nginx/1.8.0
  < Content-Type: application/json; charset=utf-8
  < Status: 200 OK
  < X-UA-Compatible: IE=Edge,chrome=1
  < ETag: "3896733480aca83602457117b93f6d2b"
  < Cache-Control: max-age=0, private, must-revalidate
  < Set-Cookie: _eol_session=BAh7BkkiD3Nlc3Npb25faWQGOgZFRkkiJWFjNjIxODZlOGVmYmQ4NmU5MDljYmY5ZDYzZjA5NTJlBjsAVA%3D%3D--c86814aeba2eef948d2a8b77a72068c6e7899ee8; path=/; HttpOnly
  < X-Request-Id: 6e2227cb7d8d15ed185d045a10050421
  < X-Runtime: 20.328478
  < X-Rack-Cache: invalidate, pass
  < Content-Length: 81
  < Accept-Ranges: bytes
  < Date: Tue, 10 Nov 2015 17:00:15 GMT
  < X-Varnish: 1416841537
  < Age: 0
  < Via: 1.1 varnish
  < Connection: keep-alive
  < 
- Connection #0 to host eol.org left intact
  "Collection create failed. Check if there is a problem in the passed parameters.

**Comment by JRice** [comment]
Sorry! I closed this ticket only because the intent of it is captured in
another ticket (sorry, I'm rushing, won't look it up right now). Meant to
comment to that effect, but ... I was rushing, meeting was running long. :)
 (I am noticing a trend, here.)

We need to do more work: namely, the performance suffered due to the number
of validations, so we need to code some "batch processing" of collection
items to get both validations and commits. This will take a while longer,
sorry.

**Comment by jhpoelen** [comment]
@JRice thanks for your prompt reply! I'll wait patiently to be notified of the next iteration of the collection write api. If you have any ideas on on alternate ways to follow your activity, please do let me know.

**Comment by JRice** [comment]
Sorry, it's such a small team right now (with no real project management to
speak of ATM because we're all developers and we need
all-hands-on-development) that there's no single clear path to following
development.

As you _may_ have noticed, I/we _are_ trying to get better at keeping up
with things, but there are huge challenges in the background that we're
trying to surmount, and it means that we're generally rushing when handling
"administrative" tasks.  :D

Apologies. Things will get better. :)

**Comment by jhpoelen** [comment]
@JRice No need to apologize and thanks for all the hard work!
