### ISSUE TITLE
TraitBank records from a deleted resource are still visible in the data tab

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#334]
eg: http://eol.org/pages/1179469/data#data_point_44906367

**Comment by menna-hedaia** [comment]
Solved. The bug is fixed on the following branch
 https://github.com/EOL/eol/commit/f7ec7474343dc04acc0373767bec6628c5b0d742

**Comment by JRice** [comment]
Would you please merge that to master?

Thanks

**Comment by jhammock** [comment]
@jhammock will make a new ticket to clean up previously deleted resources.
