### ISSUE TITLE
API should return table of ratings for a data object

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#336]
At the moment, the pages and data objects API both return a single average rating for an object. It would by useful to break this down a little more, since many objects may have only received a single rating, which could be rather inaccurate.

@JRice says: "I really hate average ratings and would love to see a hash of # of votes at each rank returned instead."

Nevertheless, I suggest that the average rating is a useful summary, and maybe should be returned by default, as it is at the moment. However, when details=True is requested, the API (both pages and data objects) could also return more detail as per @JRice's suggestion.

**Comment by hyanwong** [comment]
This is done and live. Can it be closed?

**Comment by JRice** [comment]
It can.
