### ISSUE TITLE
Hierarchy entry "Not recognized by any of the available classifications"

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#337]
http://eol.org/pages/42990110/names

This shouldn't be possible.  In the overview, it says "Taxon recognized by BHL: BioDivLibrary's photostream"  
http://eol.org/pages/42990110/overview

**Comment by HudaSoliman** [comment]
Hi @KatjaSchulz, 
Can you explain why it isn't possible? 
Thanks.

**Comment by KatjaSchulz** [comment]
Hi @HudaSoliman, 

It looks like the problem has resolved itself.  It now says Taxon recognized by BHL: BioDivLibrary's photostream" in the names tab where it said "Not recognized by any of the available classifications" before.

A hierarchy entry that's "Not recognized by any of the available classifications" should be impossible on EOL because all hierarchy entries originate from partner resources, and they would then be recognized by the classification of that resource.

This ticket can now be closed.  I will merge this hierarchy entry to another concept.
