### ISSUE TITLE
Search for "Great Blue Heron" has "no matches" in autocomplete

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#339]
...I am _pretty_ sure this is caused by a single match not returning an array, but telling the page to redirect. ...But we don't want that behavior for autocomplete_taxon.

**Comment by HudaSoliman** [comment]
Hi @JRice 
I tested ur example and it gives the expected taxon. Is there another example for this? (tested from cell phone due to the blocking issue)
![eol](https://cloud.githubusercontent.com/assets/10114312/18305234/e072d444-74e6-11e6-94bb-72202e5818c7.png)

**Comment by JRice** [comment]
No, I am pretty sure this is resolved... It was certainly an indexing problem.
