### ISSUE TITLE
Delete TB records associated with previously deleted resources

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#341]
In the past, TraitBank records persisted when their resources were deleted. (fixed in https://github.com/EOL/tramea/issues/334)

There are TB records remaining from resources deleted during this period. eg: http://eol.org/pages/1179469/data#data_point_44906367

These should be deleted.

**Comment by AmrMMorad** [comment]
This is estimable task not bug in its meaning. In fact this also can be divided into 2 different major parts:
- Identify deleted resources ids which still have traitbank records.
- Delete the triples from virtuoso.

This can be done in a separate script to run only once. I think we need to create the corresponding task in Jira.

**Comment by AmrMMorad** [comment]
addressed in jira see https://eol-jira.bibalex.org/browse/TRAM-285
