### ISSUE TITLE
new apple-touch-icon errors

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#342]
These are harmless but quite frequent and are clogging the logs. Previous similar errors were cleaned up in https://github.com/EOL/tramea/issues/139

New errors to be cleaned up:

apple-touch-icon-120x120.png
/apple-touch-icon-120x120-precomposed.png
/apple-touch-icon-152x152-precomposed.png
/apple-touch-icon-152x152.png

**Comment by HudaSoliman** [comment]
I added a gem called 'quiet_safari' that prevents those errors, the fix is on the master branch now waiting for deploy.

**Comment by jhammock** [comment]
I think this has been deployed. Is it working?

**Comment by JRice** [comment]
I believe so!
