### ISSUE TITLE
[5] create collection times out when providing many items in collection: try batch-processing of iterms

### ISSUE THREAD

**Issue by jhpoelen** [EOL/tramea#35]
Steps to reproduce:
1. use eol write api (e.g. http://effechecka.org) to create a collection with many items (>20)

expected results: collection is created within 30 seconds.

actual results: collection is not created within 30 seconds and request times out.

**Comment by jhpoelen** [comment]
Here's a collection that timed out while creating collection using the write api: http://eol.org/collections/119599 . For some reason, it shows an error page whenever I try to look at the collection. My collections page does show a collection with the expected 129 items. The related eol ids are:

1045998
1046715
1046720
1047043
1047342
1047918
1048011
1048566
1048731
1048943
1048951
1048953
1048958
1048964
1048966
1048973
1048975
1048976
1048977
1048978
1048993
1048999
1049002
1049024
1049046
1049085
1049123
1049164
1049166
1049187
1049278
1049333
1049342
1049343
1049365
1049366
1049378
1049399
1049431
1049439
1049471
1049474
1049475
1049516
1049518
1049546
1049547
1049549
1049551
1049563
1049565
1049569
1049581
1049606
1049630
1049640
1049760
1049762
1049773
1050134
1050260
1050633
1050637
1050707
1050834
1050872
1050919
1051187
1051309
1051310
1051322
1051398
1051989
1051993
1052017
1052056
1052072
1052079
1052536
1052548
1052592
1052644
1052646
1052728
1052763
1052765
1052768
1052968
1053001
1053011
1053023
10964109
1177464
1177485
1177531
1177536
1177539
1178181
1178497
1178577
12120713
913186
914528
914551
915104
915489
915655
915860
916843
917151
917154
917490
917605
918159
918802
918803
918911
918912
918920
919946
921032
921033
921034
922241
922253
922651
922653
922655
922693

**Comment by jhammock** [comment]
One variant behavior: this collection was created for me: http://eol.org/collections/119689

with 59 of the expected 732 taxa (list:https://dl.dropboxusercontent.com/u/33761226/eolpageids.csv)
(Some of the EOL taxa were asked for multiple times, in case that matters. )

The created collection was visible at first, but now gives me this error:

Error 503 Service Unavailable
Service Unavailable
Guru Meditation:
XID: 1368133138

**Comment by jhpoelen** [comment]
Regarding the duplicate ids: no duplicates ids were submitted to the eol write api. This issue was fixed in effechecka a while ago. 

I was able to load http://eol.org/collections/119689 just now, only very slowly. Suspect that a timeout is in play.

**Comment by HudaSoliman** [comment]
You can find the fix on this branch: https://github.com/EOL/eol/tree/git35
