### ISSUE TITLE
EOL Data Search is down (Oops Error)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#350]
It was working yesterday. Possibly related to this deploy?

**Comment by JRice** [comment]
Ooops. Resolved.

**Comment by jhammock** [comment]
Arg! The page appears now, but attempting to search still produces the oops error. I _think_ the searches are not initiated (I don't see them in the Data queue, anyway).

**Comment by JRice** [comment]
Ooops. Reresolved.
