### ISSUE TITLE
nice, reformed API user, has been un-blocked but still having access problems

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#358]
Hello! This user has had one IP address unblocked, but _something_ is apparently still blocked. A machine, possibly? He is now cooperating and using a key, hence the unblocking of the IP address. His testimony:

I confirm that I am able to access the EOL API using an API key from the IP address 195.221.175.168
From my server (taxamart.cloudapp.net or taxamart.floristic.org or 23.97.187.30), I am not able to access API even if I use the same key.

Best regards,

Antoine

**Comment by JRice** [comment]
He should be good to go, now.

**Comment by jhammock** [comment]
He's in! Thanks
