### ISSUE TITLE
New gallery terms not showing their name

### ISSUE THREAD

**Issue by millerse** [EOL/tramea#359]
I have been adding some new terms to the EOL data glossary.  Each time I do, the name on the list appears as Unknown!.  (See [here](http://eol.org/known_uris?page=8&uri_type_id=3) you click the individual term you can see the name.

**Comment by JRice** [comment]
Almost certainly caching. Reading those things is REALLY slow (in the old
EOL codebase), so we cache them super-aggressively.

I think they have a two week timeout.  :\

**Comment by millerse** [comment]
Thanks for the reassurance.
