### ISSUE TITLE
[5] collections JSON response needs proper pagination

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#39]
This is NOT the "write API" and this is not the "normal" API, this is actually the "json" handler in the collections controller. Right now, it doesn't return more than one page of collection items, so we need to add an attribute for that and make sure it returns a second page of items.

**Comment by JRice** [comment]
https://github.com/EOL/eol/blob/master/app/controllers/collections_controller.rb ...the format.json block needs to handle two params: page and per_page, and return the appropriate results (you should be able to use the will_paginate code that's used elsewhere for this).

**Comment by hyanwong** [comment]
Pagination for the pages API would be useful too (if >75 data objects are returned)

**Comment by AmrMMorad** [comment]
@hyanwong: Do we still have this issue?

**Comment by hyanwong** [comment]
@AmrMMorad I think so. From http://eol.org/api/docs/pages I can't see how to get (e.g.) the 76th image on a page via the API. I'm not sure how this should be set up re: pagination. Or perhaps the 'images' parameter should take a range, rather than a single number?

**Comment by AmrMMorad** [comment]
@hyanwong In fact with my question I meant the original issue of the collection JSON response. But in the pages API, image parameter (for example) represents the images' number returned not a specific image to be returned.

**Comment by hyanwong** [comment]
@AmrMMorad I don't know about collections. But currently there is no way to get the 76th image on a page like http://eol.org/pages/1/media (and there are 1768553 images which you might want!)

**Comment by JRice** [comment]
FWIW: The original purpose of this ticket does actually work, e.g.: 

http://eol.org/collections/22117.json?page=4
