### ISSUE TITLE
[5] Enable CORS for API

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#41]

**Comment by AmrMMorad** [comment]
A solution for this is under:
https://github.com/EOL/eol/compare/git-41
There is a gem called rack-cors used to enable CORs headers for API. CORs headers can be _controlled_ using parameters in application.rb file. Currently I enabled these headers for ALL origins and for ALL resources under wapi. I restricted these headers to get, post, options and put HTTP methods only. This can be changed easily in application.rb file so to guarantee security more.

**Comment by JRice** [comment]
Looks good, thanks. Nice and clean.

Could you merge this to master?

**Comment by AmrMMorad** [comment]
Sure, Done now..
Thanks

**Comment by hyanwong** [comment]
This does not currently seem to be working, see https://github.com/EOL/tramea/issues/147
