### ISSUE TITLE
Reply link on comments not visible (though it works on Activity Logs e.g. "Joined community")

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#46]

**Comment by AmrMMorad** [comment]
A solution for it is under:
https://github.com/EOL/eol/compare/git-46

**Comment by JRice** [comment]
Oh, man, I _hate that problem._ (It comes up in several places in views.)

Thanks.

...Could you push that to master, please?

**Comment by AmrMMorad** [comment]
Done... Sorry for not doing this yesterday as I had some conflicts on my workspace.
Thanks
