### ISSUE TITLE
Cannot add new records to URI registry

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#58]
http://eol.org/known_uris

I can enter the information for a new uri in the form, but when I try to save my entry, I get an error.  Checking the list of uris, I see that my entry was not saved.

**Comment by menna-hedaia** [comment]
I checked your issue , it has been solved , just waiting for the next deployment.

**Comment by JRice** [comment]
Let JR look at this, actually: could be a production-specific problem! Sorry!
