### ISSUE TITLE
No statistics for BHL content

### ISSUE THREAD

**Issue by KatjaSchulz** [EOL/tramea#59]
The BHL folks noticed that statistics for BHL content on EOL appear to be broken:
http://eol.org/statistics

We have 0 values for Pages with BHL links, Pages with BHL links but no text, and Pages with BHL links only

Did the code for these stats get left behind somewhere during the migration?

**Comment by KatjaSchulz** [comment]
I don't seem to be able to assign labels to issues here, so I can't mark things as bugs.

**Comment by JRice** [comment]
I don't believe they _were_ left behind, but they _definitely_ failed last
night; it's one of the things I've mentioned in chat today (I've yet to
turn findings into a coherent email, sorry).

I will try re-running them tonight.

**Comment by KatjaSchulz** [comment]
Values have been zero for a while though: http://eol.org/statistics?utf8=%E2%9C%93&date_one%5Bday%5D=15&date_one%5Bmonth%5D=11&date_one%5Byear%5D=2015&date_two%5Bday%5D=30&date_two%5Bmonth%5D=11&date_two%5Byear%5D=2015&date_one_set=2015-11-23&date_two_set=2015-11-30

**Comment by JRice** [comment]
Okay, thanks. We'll make it bug, then.

**Comment by YoustinaAtef** [comment]
TaxonPageMetrics.php read this file:
eol_php_code/applications/taxon_page_metrics/text_files/taxon_concept_with_bhl_publications.txt
to calculate BHL_publications, but this file is empty so that it's calculations = 0

There is a rake task that generate this file which is "generate_bhl_text_files.php" but it seems that it isn't called anywhere.

**Comment by JRice** [comment]
I've started the job running on the harvest machine to see if it'll help, but I can't help but notice the script says "Work in Progress" in it, soooo...

It's possible this was something that had pieces abandoned on the old harvest machine. :(

```
www-data 104726 104708  0 10:34 ?        00:00:00 php applications/taxon_page_metrics/generate_bhl_text_files.php
```

**Comment by JRice** [comment]
I don't know what happened to that script, but it ran. ...Could someone at BA check on the status of things now?

**Comment by HudaSoliman** [comment]
fixed. You can check it on the site:  http://eol.org/statistics

**Comment by jhammock** [comment]
Beautiful, thanks!
