### ISSUE TITLE
(oldeol) Dedicate some time to ensuring Name Resolution is back on track

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#6]
Putting this in here just so we have all tickets in one place.

**Comment by JRice** [comment]
This may require re-harvesting NHM resource. ...which apparently failed recently.

**Comment by JRice** [comment]
Q: Are there other resources which are missing their names data in Solr? Can we programmatically test this?

**Comment by JRice** [comment]
NMNH resource is the resource that had the names resolution problem. ...Let's do that and see if that works. (I worry the created taxa will be retained—we need to manually fix that if that happens.)

**Comment by HudaSoliman** [comment]
I wrote a script if there are missing resources from solr and the results were 3 resources:
1- NHM Type Specimen Resource:  http://eol.org/content_partners/381/resources/947
2- Wikipedia - German: http://eol.org/content_partners/129/resources/957
3- Feller: http://eol.org/content_partners/494/resources/958
Currently, I added some debug messages to trace the harvesting, and it's waiting now for re-harvesting those resources.

**Comment by JRice** [comment]
Great! Thanks much. I've already put your new code in production; I am
going to choose the smallest of these ("Wikipedia - German") to run today.
