### ISSUE TITLE
[5] Implement true/false 'taxonomy' API parameter to reduce size of returned data in the API

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#60]
As a precursor to API batch mode (https://github.com/EOL/tramea/issues/40), implement a new parameter in the [pages API](http://eol.org/api/docs/pages) and  [data objects API](http://eol.org/api/docs/data_objects), to make requests without returning "taxonConcepts" results. I suggest a new API parameter with a title such as 'taxonomy' (default=true), whose description could be something like 'return any taxonomy details from different taxon hierarchy providers, in an array named "taxonConcepts"'. 

Currently the "taxonConcepts" array is always returned by a pages or data_objects API call. This parameter should enable API calls that return less superfluous information.

**Comment by hyanwong** [comment]
Just changed the title and description: previously I suggested we needed an 'overview":"none" option, but I now see that overview texts can be omitted from the results by setting 'text':0

**Comment by JRice** [comment]
Just want to take a second to say: nice ticket! Good suggestion, lots of detail, plenty of description of what you want and why you want it. Impressive.

Nice, thanks!

**Comment by hyanwong** [comment]
Thanks. All that is needed is to implement it then :)

**Comment by AmrMMorad** [comment]
@hyanwong: I didn't see taxon concepts array returned from data objects API. I believe it returns name, references and some "object" attributes such as identifier, data-type, title and etc. Am I missing something here?
Thanks!

**Comment by hyanwong** [comment]
If you go to http://eol.org/api/docs/data_objects and click on "Call API" in the "Test It Out" section, you'll see a 'taxonConcepts' section in the returned data. Or go to http://eol.org/api/data_objects/1.0/30073527.json?cache_ttl=

**Comment by AmrMMorad** [comment]
kindly find a solution for that under:
https://github.com/EOL/eol/compare/git-60

**Comment by hyanwong** [comment]
This isn't live yet, is it? If so, it needs the documentation changing at http://eol.org/api/docs/data_objects

**Comment by JRice** [comment]
Nono, closed only insomuch as the development process requires closing tickets for planning. It still needs to be merged to master and pushed to production, which is part of a different process. 

...Apologies if this feels "wrong" ... we're used to working with Jira, which has a very different workflow, so we're kind of bastardizing Github's issues, and probably haven't found "the right way to do it". :\  ...Not enough time to devote to process tweaks right now, either. :(
