### ISSUE TITLE
[5] Pages & data objects APIs - remove empty returned arrays

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#62]
Not entirely backwards compatible, but I suggest that when a pages API request is made with e.g. 'common_names':'False', or 'synonyms':'False', the returned JSON should NOT include an empty "vernacularNames" / "synonyms" value. Currently the returned value will include e.g.

```
"vernacularNames": []
```

which is unnecessary, and will take up extra space once we implement an API batch mode (https://github.com/EOL/tramea/issues/40). The same applies not just to "vernacularNames" and "synonyms", but also "references", "taxonConcepts", and "dataObjects".

**Comment by hyanwong** [comment]
This should probably also be the case in the data_objects API.

**Comment by HudaSoliman** [comment]
code for this task is found on this branch: https://github.com/EOL/eol/compare/git-62

**Comment by hyanwong** [comment]
Great. I don't follow Ruby, so can't check, but wanted to check that this will still return (say) an empty "vernacularNames" array if "vernacularNames":"True" was specified in the API call, but no vernacular names exist in the DB? the empty arrays should only be killed off if "vernacularNames":"False" was requested.

@JRice are you happy with this, since it is a minor API change? Would we need to bump the API number?

**Comment by HudaSoliman** [comment]
@hyanwong Let me make sure about this ,you want to kill any empty array unless it's required ( passed as true? ) , Right? Since data_objects api doesn't have any optional parameters.

**Comment by hyanwong** [comment]
Yes. So if  a user wants (say) up to 2 images, they are likely to make an pages API request with "images"=2, then expect there to be a dataObjects array to iterate over containing (up to) 2 images. Even if there are no images, it presumably would be useful to have an empty array returned in this case, so that they don't have to check for existence before iteration. But if they don't request any data objects (e.g. images=0, text=0, etc etc, and just make the API request to get (say) synonyms, then there is no point returning the dataObjects array at all. Does that make sense? Is it sensible?

**Comment by HudaSoliman** [comment]
Yes, it makes sense. But, if the TaxonConcepts array is empty we should kill it too, right? and in the data_objects api we should kill any empty array ?

**Comment by hyanwong** [comment]
For the pages API: We should kill the TaxonConcepts array if (one only if) the API request has been made with TaxonConcepts="False". We should kill the dataObjects array if (and only if) the API request has been made such that no data objects are ever expected to be returned - i.e. Images=0, AND videos=0, AND sounds=0 (or undefined), AND maps=0 (or undefined), AND text=0 (also, I'm not sure if IUCN returns a dataObject). We should kill the references array if (and only if) the API request has been made with references=False, and so on.

For the data_objects API, we should similarly kill the TaxonConcepts array if (one only if) the API request has been made with TaxonConcepts="False". I'm not sure if we should ever kill the _dataObjects_ array in the data_objects API: that would seem a bit weird, given the name of the API. In other words, for the dataObjects API, I suspect we should _always_ return a dataObjects array, even if it is empty. 

I guess the only reason you might not want to return a dataObjects array is if people are using the dataObjects API to get TaxonConcepts for a data object. If you think this is a reasonable use case, there might be an argument for having another parameter to the dataObjects API such as "details:True", which could be set to False if the user was interested in only getting TaxonConcepts for that data object. But that's probably an unusual use case so can probably wait until a further iteration, unless you are keen to code it up.
