### ISSUE TITLE
Missing translation on Data Search page

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#63]
http://eol.org/data_search

...Under "Select an attribute", the dropdown begins with a missing translation (which, I believe, is actually supposed to be a repeat of "Select an attribute," ironically.

I'm pretty sure the translation DOES exist, so something else is amiss; perhaps the way I18n.t is called.

**Comment by YoustinaAtef** [comment]
The problem is solved locally by cleaning assets using this command 
bundle exec rake assets:clean RAILS_ENV=development rails_group=assets
