### ISSUE TITLE
API returns seemingly random languages

### ISSUE THREAD

**Issue by hyanwong** [EOL/tramea#72]
At times, APIs (e.g. the [data objects API](http://eol.org/api/docs/data_objects) returns results with different language localisations. E.g. one moment:

``` bash
> curl -s http://eol.org/api/data_objects/1.0/27183928.json?cache_ttl=50 | grep -o 'agents.\{0,200\}'
agents":[{"full_name":"Tiit Hunt","homepage":"http://commons.wikimedia.org/wiki/User:Tiithunt","role":"photographer"},{"full_name":"Wikimedia Commons","homepage":"http://commons.wikimedia.org/","role":"prov
```

and the next

```
>curl -s http://eol.org/api/data_objects/1.0/27183928.json?cache_ttl=50 | grep -o 'agents.\{0,200\}'
agents":[{"full_name":"Tiit Hunt","homepage":"http://commons.wikimedia.org/wiki/User:Tiithunt","role":"\u651d\u5f71\u8005"},{"full_name":"Wikimedia Commons","homepage":"http://commons.wikimedia.org/","role"
```

(note the language change in the 'role' result)

**Comment by hyanwong** [comment]
NB, from the outside this appears a highly intermittent issue. Many days can go by without it happening, and then it will appear, often with different languages each time a call is made (one second chinese, next german, next greek, etc etc.)

**Comment by JRice** [comment]
I've looked at the code and see the problem. I am going to let one of the BA devs resolve this, but basically they are just going to have to set the locale when the API is called, with e.g.: `I18n.locale = :en`

...I think that when they're at it, they might want to put this in `validate_and_normalize_input_parameters!` and modify that method to accept (universally) a "language" parameter with a default value of "en" ...so all of the APIs will be able to specify what language to provide the results with. It's a pretty complicated method, so this isn't simple, but it would be very handy!

**Comment by hyanwong** [comment]
BA devs are currently handling API changes I have suggested such as https://github.com/EOL/tramea/issues/62 and https://github.com/EOL/tramea/issues/60, so your latter suggestion is just more of the same, and presumably a good time to do so.
