### ISSUE TITLE
[5] investigate anti-spam methods

### ISSUE THREAD

**Issue by JRice** [EOL/tramea#83]
Someone should do a little research on what modern Rails sites do to avoid users creating "spammy" content.

This is not a ticket requiring any code be written; it is only intended for research.

**Comment by AmrMMorad** [comment]
Modern sites use one or a combination of more than one technique from the following:
- Use recaptcha to prevent bot attacks. Recaptch is already used in EOL for signup process. Some resources suggest to use it also for other processes such as creating a comment, collection and etc. The problem with this technique is that the user will be annoyed and may not participate in EOL.
- Check whether the creation process of a resource (comment, collection and etc..) takes very short time. This indicates bots attack. For example if a comment is written within milliseconds so this will indicate bots attack.
  An example for this is under:
  http://blog.gingerlime.com/2012/simple-detection-of-comment-spam-in-rails/
- Project honeypot. This requires adding a hidden field which has an "interesting" name for bots. This field will be hidden for the users. So if the user is a human, the form will be submitted without this field. If the bot is trying to attack this form, then it will fill in this field and then spam can be detected.
  More about this is under:
  http://nomethoderror.com/blog/2014/02/26/simple-rails-form-honeypot/
  http://www.sitepoint.com/easy-spam-prevention-using-hidden-form-fields/
- Use ipaddress gem. This gem is used to block certain ip addresses from doing a certain action on the rails site as in the following:
  https://github.com/bluemonk/ipaddress
- Add a flag button besides each resource which can be spammed. For example add "Mark as a spam" button besides a comment or a collection and leave the admin/curator to take the decision. A new page can be implemented for admins or curators where they can handle and take the correct decision (whether to approve or refuse this claim).
- Use stuff classifier gem: This gem is used to classify text into multiple categories. It implements one of the most powerful categorization algorithms which is naive bayes theorem. This can be used to classify a resource to a spam or ham. More information can be found:
  https://github.com/alexandru/stuff-classifier
- Use filter spam gem. This gem provides spam filter functionality by building bag of words. More info is:
  https://github.com/resolve/filters_spam
- Use Rakismet gem. This gem depends on akismet (http://akismet.com/) which is a collaborative spam filtering service. This one was the most commonly used gem to detect spams in rails sites. Using it will require 5$/month fees. More information can be found under:
  https://github.com/joshfrench/rakismet
- Use defensio gem. This gem provides spam filter service also and is one of the most common methods used currently. More can be found under:
  https://github.com/defensio/defensio-ruby
  Note that both Rakismet and defensio depends on bag of words technique and bayes theorem to calculate the likelihood of a comment or collection to be a spam.
- Use vikings gem. This gem is used to combine both rakismet and defensio and easy to use. More information is under:
  https://github.com/dimelo/viking
