### ISSUE TITLE
[5]add "noindex" tag to hidden or removed pages to keep them out of search engines

### ISSUE THREAD

**Issue by BobCorrigan** [EOL/tramea#85]
After the recent spam attack on EOL, it's become clear we need to ensure that bad content - if not completely removed from the EOL database - is at least appropriately marked to ensure it doesn't end up in Google or other search engines. The overall page rank and reputation of EOL is negatively impacted by bad content, so this is urgent.

Google documents two approaches (source: https://support.google.com/webmasters/answer/81749/?utm_source=wnc_634403&utm_medium=gamma&utm_campaign=wnc_634403&utm_content=msg_694100&hl=en): use of "nofollow" tags on links and "noindex" tags on pages.  

I propose the latter be employed on all pages that have been either hidden or disassociated from taxon pages.  

**Another approach could be to simply tag ALL taxon object pages as "noindex".  It would remove a lot of pages from the Google cache.  I am not sure what this would mean to our site map.**

FYI re: NOINDEX (excerpted from the above link):

**Prevent untrusted content from showing in search**

If your site allows users to create pages like profile pages, forum threads, or websites, you can deter spam abuse by preventing new or untrusted content from showing up in search.

For example, you can use the noindex meta standard to block access to pages for new and not-yet-trusted users. Like this:

Or you can use the robots.txt standard to temporarily block the page:

Disallow:/guestbook/newpost.php
Once you believe the user is legitimate and not a spammer, you can remove the crawling or indexing restrictions. There are a number of ways that you can tell if a new user is a spammer, including using signals from your community.

Recommended approaches:

Physically remove offending pages from the EOL database. If it's not there, it can't be crawled.

When a page containing spam content is marked "hidden" or disassociated with a taxon, it should be marked "nofollow" per recommendation 1 above. This is the most urgent of the activities to prevent future issues.

Pages on the site that are at risk of abuse by users (e.g., user profiles) should be marked "noindex"

**Comment by YoustinaAtef** [comment]
I added "nonindex" tag to unpublished data_object pages.
Comments are not displayed if they are hidden, 
common names are being destroyed and collections are left published and visible, so that nothing was done for handling them.
branch for this issue:
https://github.com/EOL/eol/compare/collection.scrub%2880%29
