### ISSUE TITLE
Error message when trying to add a new translation in CMS

### ISSUE THREAD

**Issue by tbarbaroeol** [EOL/tramea#91]
Error message when trying to add a new translation in CMS. See attached image. When you click on "add translation" you get an error message, 
"Oops. We're sorry, we have encountered a problem. If the problem persists, please send email to error@eol.org"

![image](https://cloud.githubusercontent.com/assets/14058411/12562784/f1f94924-c374-11e5-8c96-7c93d717c287.png)

**Comment by YoustinaAtef** [comment]
This is fixed and pushed to master.
