### ISSUE TITLE
TraitBank - Data term info boxes sometimes missing (post release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#95]
The "?" boxes that display info for a data term (URI, definition, etc.) are sometimes missing.

**Comment by jhammock** [comment]
There may be a pattern. I haven't found this problem with measurement type terms, only with value terms. And it's possible that it's only happening to habitat value terms. I'm less confident of the second distinction, because we don't have many other value terms in the beta TraitBank. If it's just the habitat terms, they have a lot in common- they're all from the ENVO ontology and they were all brought in together in a batch import from an .owl file, using the known uris tool. We've only done that kind of import that one time.

Hope that helps!

**Comment by jhammock** [comment]
Not just habitat, it turns out. Some values of TypeSpecimenRepository are also affected. Still just values, though.

**Comment by menna-hedaia** [comment]
Fixed. The solution is on this branch 
https://github.com/EOL/eol/commit/73e2bd536907874fd42b13e7059a2d7166a94ef3
