### ISSUE TITLE
TraitBank - unwanted prompt text, "translation missing",  in TB search box (post release)

### ISSUE THREAD

**Issue by jhammock** [EOL/tramea#98]
Jeremy hasn't been able to track down the cause of this. Anyone else care to try?

**Comment by YoustinaAtef** [comment]
I tried to visit this link eol.org/data_search, but I got "Sorry, this feature is temporarily disabled. Check back soon."
How could you know that this "translation missing" is still there?

**Comment by YoustinaAtef** [comment]
This is fixed here --> https://github.com/EOL/eol/compare/tbs_translation_missing
You need to clean assets and recompile them before the next deploy.

**Comment by JRice** [comment]
Could you merge this to master, please?

**Comment by YoustinaAtef** [comment]
Done.
